src/objects/Community_Event_Tag__c.object
<CustomObject>
    <description>This object allows Tags and a Group to be associated to an Event record.</description>
    <fields>
        <fullName>Community_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated with this Event record.</description>
        <label>Community Event</label>
        <referenceTo>Community_Events__c</referenceTo>
        <relationshipLabel>Group &amp; Tags</relationshipLabel>
        <relationshipName>Events_Tag_Joins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Group_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows a Community Group to be associated with a Community Event.  Not mandatory.  Only used when joining a Community Event to a Chatter Group.</description>
        <label>Community Group Control</label>
        <referenceTo>Community_Group_Control__c</referenceTo>
        <relationshipLabel>Group Events</relationshipLabel>
        <relationshipName>Community_Event_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated with this Event record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>Event Items Tagged</relationshipLabel>
        <relationshipName>Community_EventItems_Tagged</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Event Tag</label>
    <nameField>
        <displayFormat>CET-{yy}{mm}{0}</displayFormat>
        <label>Community Event Tag</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Event Tag</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Events__c.object
<CustomObject>
    <description>Used to store Events in the Community.  Events may or may not be associated with a Group.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Provide a description of the Community Event details and RSVP instructions (if any)</description>
        <label>Description</label>
        <length>10000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <description>End Date/Time of the Community Event</description>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Used to define a name for the event.  This field is mandatory.</description>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>Start Date/Time of the Community Event Record</description>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Teaser__c</fullName>
        <description>Provide a teaser description for the Event, to be displayed on the Event Listing page within the Community.</description>
        <inlineHelpText>The Teaser is shown on the Event Listing page for Events that are flagged as Public.</inlineHelpText>
        <label>Teaser</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <label>Community Event</label>
    <nameField>
        <displayFormat>EVENT.{yy}{mm}{0}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Group_Control__c.object
<CustomObject>
    <description>Represents the metadata associated with a Chatter Group that is created in the Community.  Is used to serve up the Group Manager feed separately from the Chatter Group Feed.</description>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This defines the 18-digit SFID of the related Chatter Group for the Group Control record.</description>
        <label>Chatter Group ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Defines a description for the Group Control which will also be related to the Chatter Group, if needed.</description>
        <inlineHelpText>Write a brief description of your group.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Discoverable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Discoverable = TRUE, the related Group will be visible in the Community for non-members to view</description>
        <inlineHelpText>If your group is discoverable, other users may find and view the group feed.  If your group is not discoverable, other users will not be able to find the group and members must be added by a group manager.</inlineHelpText>
        <label>Discoverable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <description>This field defines which Community the Chatter Group will be created in.  If there is only one Community, use &quot;Community.&quot; If there are multiple Communities, use the Community Names as values for this field.</description>
        <label>Network</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Community</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Represents the Type of Group that will be created in the system.</description>
        <inlineHelpText>If your group will be public, any user may join.  If your group will be private, members must be added by a group manager.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Group Control</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Group Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Group_Control__c.object
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field defines whether the related group is Active in the Community and visible to users.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>

objects/Community_Group_Control__c.object
    <fields>
        <fullName>Automatic_Archive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field defines whether automatic group archiving rules will apply to the related group.</description>
        <label>Automatic Archive</label>
        <type>Checkbox</type>
    </fields>

src/objects/Community_News__c.object
<CustomObject>
    <description>This object stores News stories (links or text content) that are published to the Community.</description>
    <fields>
        <fullName>Allow_Comments__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When selected, Community Users will be allowed to post Comments on a news article as long as the Comment Expiration has not passed.</description>
        <inlineHelpText>When selected, Community Users will be allowed to post Comments on a news article as long as the Comment Expiration has not passed.</inlineHelpText>
        <label>Allow Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <description>Represents the Date/Time when the News Article will be posted in the Community Portal.  This will be based on the Organizations Time Zone in Salesforce.</description>
        <inlineHelpText>Represents the Date/Time when the News Article will be posted in the Community Portal.  This will be based on the Organizations Time Zone in Salesforce.</inlineHelpText>
        <label>Entry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Represents the Date/Time when the News Article will be removed from the Community Portal.  The time will be based on the Organizations Time Zone in Salesforce.</description>
        <inlineHelpText>Represents the Date/Time when the News Article will be removed from the Community Portal.  The time will be based on the Organizations Time Zone in Salesforce.</inlineHelpText>
        <label>Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Make_Entry_Sticky__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When selected, the News Article will always appear at the top of the News Article Listed.  If multiple active Sticky, articles will be listed in Descending Order by Entry Date field.</description>
        <inlineHelpText>When selected, the News Article will always appear at the top of the News Article Listed.  If multiple active Sticky, articles will be listed in Descending Order by Entry Date field.</inlineHelpText>
        <label>Make Entry Sticky</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Teaser__c</fullName>
        <description>Represents a short description of the News article that will be posted in the Community Portal.</description>
        <inlineHelpText>Represents a short description of the News article that will be posted in the Community Portal.</inlineHelpText>
        <label>Teaser</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Represents the title of the news that will be displayed in the Community Portal.</description>
        <inlineHelpText>Represents the title of the news that will be displayed in the Community Portal.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates the type of news that is being added.  Internal represents a news article pasted into Salesforce and an External would be a link to an article posted somewhere on the internet.</description>
        <inlineHelpText>Indicates the type of news that is being added.  Internal represents a news article pasted into Salesforce and an External would be a link to an article posted somewhere on the internet.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community News</label>
    <nameField>
        <displayFormat>News.{yy}{mm}{0}</displayFormat>
        <label>News</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_News_Tag__c.object
<CustomObject>
    <description>This object allows Tags to be associated to a Community News record.</description>
    <fields>
        <fullName>Allow_Comments__c</fullName>
        <description>Indicates if the related News article allows user&apos;s to comment on it.</description>
        <formula>Community_News__r.Allow_Comments__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The News article allows user&apos;s to comment on it.</inlineHelpText>
        <label>Allow Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Community_News__c</fullName>
        <description>Allows tags to be associated with this Community News record.</description>
        <label>Community News</label>
        <referenceTo>Community_News__c</referenceTo>
        <relationshipLabel>News Tags</relationshipLabel>
        <relationshipName>Community_News_Tag</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <description>Defines the tag that is being associated with the News record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>News Items Tagged</relationshipLabel>
        <relationshipName>Community_NewItems_Tagged</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community News Tag</label>
    <nameField>
        <displayFormat>CNT-{yy}{mm}{0}</displayFormat>
        <label>Community News Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_Tag__c.object
<CustomObject>
    <description>Define a library of Tags that will help categorize interests for the Community.  Tags can be associated to Community News, Events, Groups, and Contacts via separate junction objects.  This will allow the starter pack to recommend items to a Community user.</description>
    <fields>
        <fullName>Community_Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the Theme of the Community Tag.</description>
        <inlineHelpText>Represents the Theme of the Community Tag.</inlineHelpText>
        <label>Community Theme</label>
        <referenceTo>Community_Theme__c</referenceTo>
        <relationshipLabel>Community Tags</relationshipLabel>
        <relationshipName>Community_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Tag</label>
    <nameField>
        <label>Community Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Tag__c.object
    <fields>
        <fullName>Display_in_Wizard__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines whether tags within this Theme should be visible to users during the profile registration wizard for the Community.</description>
        <label>Display in Wizard</label>
        <type>Checkbox</type>
    </fields>

src/objects/Community_Theme__c.object
<CustomObject>
    <description>Will be used to roll up Tags to a Theme.  Depending on attributes of the Theme, related Tags may be used in the Community Registration process or available to associate to Resources.</description>
    <label>Community Theme</label>
    <nameField>
        <label>Community Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Theme__c.object
    <fields>
        <fullName>Enable_in_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If TRUE, this theme will be presented to a Community user when registering for access to the community.</description>
        <label>Enable in Wizard</label>
        <type>Checkbox</type>
    </fields>

classes/Test_Community.cls
@isTest(SeeAllData=true)
private class Test_Community {
/*
	static testMethod void Test_CommunityEventController() {
		Profile profile = [SELECT Id, Name FROM profile WHERE name='System Administrator'];
		User user = new User(
			alias = 'tt01', email='testtest01@test.com', emailencodingkey='UTF-8',
			lastname='testtest01', languagelocalekey='en_US', localesidkey='en_US',
			profileid = profile.Id, timezonesidkey='America/Los_Angeles', username='testtest01111@test.com'
		);
		insert user;

		List<Community_Events__c> communityEventsList = new List<Community_Events__c>();
		Community_Events__c event1 = new Community_Events__c(Name__c='test_event_1', Description__c = 'test description', Teaser__c = '', Start__c = system.TODAY().addDays(1), End__c = system.today().addDays(2));
		communityEventsList.add(event1);
		insert communityEventsList;
		
		List <Community_Theme__c> themeList = new list<Community_Theme__c>();
		Community_Theme__c theme = new Community_Theme__c();
		theme.Enable_in_Wizard__c = true;
		theme.Name = 'TEST Theme';
		themeList.add(theme);
		insert themeList;
		
		List<Community_Tag__c> CommunityTagList = new list<Community_Tag__c>();
		Community_Tag__c tag = new Community_Tag__c();
		tag.Name = 'TEST TAG';
		tag.Display_in_Wizard__c = true;
		tag.Community_Theme__c = themeList[0].id;
		CommunityTagList.add(tag);
		insert CommunityTagList;
		
		List<Community_Event_Tag__c> CommunityEventTagList = new list <Community_Event_Tag__c>();
		Community_Event_Tag__c event_tag = new Community_Event_Tag__c();
		event_tag.Community_Tag__c = CommunityTagList[0].id;
		event_tag.Community_Event__c = communityEventsList[0].id;
		CommunityEventTagList.add(event_tag);
		insert CommunityEventTagList;
		
		List<Community_Group_Control__c> CommunityGroupControlList = new list <Community_Group_Control__c>();
		Community_Group_Control__c newtestgroup = new Community_Group_Control__c();
		newtestgroup.name = 'newtestgroup';
		newtestgroup.active__c = true;
		newtestgroup.automatic_Archive__c = true;
		newtestgroup.discoverable__c = true;
		newtestgroup.Type__c = 'Public';
		newtestgroup.Network__c = 'Internal';
		CommunityGroupControlList.add(newtestgroup);
		insert CommunityGroupControlList;
		CommunityGroupControlList[0].Chatter_Group_ID__c = 'TestGroupChatterId';
		update CommunityGroupControlList;


		System.RunAs(user) {

			test.startTest();
			ApexPages.StandardController standartController = new ApexPages.StandardController(communityEventsList[0]);

			PageReference pr = new PageReference(Page.CommunityEventDetail.getUrl() + '?cloneid='+communityEventsList[0].id + '&g=' + newtestgroup.Chatter_Group_ID__c+'&t='+CommunityTagList[0].id);
			Test.setCurrentPage(pr);

			CommunityEventController controller = new CommunityEventController();
			controller.initFromEdit();
			controller.initFromView();
			controller.initFromList();
			controller.cancel();
			controller.event = event1;
			controller.submit();
			controller.gotoCreate();
			controller.CurrentFilter = Label.LBL_New_Group_Events;
			controller.initFromList();
			controller.CurrentFilter = Label.LBL_My_Group_Events;
			controller.initFromList();
			controller.CurrentFilter = Label.LBL_My_Events;
			controller.initFromList();
			controller.nextPage();
			controller.lastPage();
			controller.previousPage();
			controller.firstPage();
			controller.pageNumber = 2;
			controller.setPageNumber();

			test.stopTest();
		}

	}
	*/
	static testMethod void Test_CommunityNewsController() {
		Profile profile = [SELECT Id, Name FROM profile WHERE name='System Administrator'];
		User user = new User(
			alias = 'tt01', email='testtest01@test.com', emailencodingkey='UTF-8',
			lastname='testtest01', languagelocalekey='en_US', localesidkey='en_US',
			profileid = profile.Id, timezonesidkey='America/Los_Angeles', username='testtest01111@test.com'
		);
		insert user;

		List<Community_Events__c> communityEventsList = new List<Community_Events__c>();
		Community_Events__c event1 = new Community_Events__c(Name__c='test_event_1', Description__c = 'test description', Teaser__c = '', Start__c = system.TODAY().addDays(1), End__c = system.today().addDays(2));
		communityEventsList.add(event1);
		insert communityEventsList;
		
		List <Community_Theme__c> themeList = new list<Community_Theme__c>();
		Community_Theme__c theme = new Community_Theme__c();
		theme.Enable_in_Wizard__c = true;
		theme.Name = 'TEST Theme';
		themeList.add(theme);
		insert themeList;
		
		List<Community_Tag__c> CommunityTagList = new list<Community_Tag__c>();
		Community_Tag__c tag = new Community_Tag__c();
		tag.Name = 'TEST TAG';
		tag.Display_in_Wizard__c = true;
		tag.Community_Theme__c = themeList[0].id;
		CommunityTagList.add(tag);
		insert CommunityTagList;
		
		List<Community_News__c> communityNewsList = new List<Community_News__c>();
			Community_News__c newsitem = new Community_News__c(Title__c='test_title', Entry_Date__c = Datetime.now(), Expiration_Date__c = Datetime.now().adddays(9), Allow_Comments__c = true, Make_Entry_Sticky__c = true, Type__c = 'External');
			communityNewsList.add(newsitem);
			insert communityNewsList;

			List<Community_News_Tag__c> communityNewsTagList = new List<Community_News_Tag__c>();
			Community_News_Tag__c NewsTag = new Community_News_Tag__c(Community_News__c=communityNewsList[0].id, Community_Tag__c = CommunityTagList[0].id);
			communityNewsTagList.add(NewsTag);
			insert communityNewsTagList;

			ApexPages.StandardController newstandartController =
			new ApexPages.StandardController(communityNewsList[0]);
			PageReference npr = new PageReference(Page.CommunityNewsEdit.getUrl() + '?&t='+CommunityTagList[0].id);
			Test.setCurrentPage(npr);
		
		System.RunAs(user) {
			test.startTest();
			
			CommunityNewsController newscontroller = new CommunityNewsController(newstandartController);
			newscontroller.initFromEdit();
			newscontroller.initFromView();
			newscontroller.initFromList();
			newscontroller.cancel();
			newscontroller.edit();
			newscontroller.imgBody = blob.valueof('testblbob');
			newscontroller.imgFileName = 'TestFileName';
			newscontroller.gotoCreate();
			newscontroller.submit();
			system.debug(newscontroller.allowComments);
			newscontroller.newsNextPage();
			newscontroller.newsLastPage();
			newscontroller.newsPreviousPage();
			newscontroller.newsFirstPage();

			test.stopTest();
		}
		
	}
	

	/*
	static testMethod void CommunityGroupsController() {
		Profile profile = [SELECT Id, Name FROM profile WHERE name='System Administrator'];
		User user = new User(
			alias = 'tt01', email='testtest01@test.com', emailencodingkey='UTF-8',
			lastname='testtest01', languagelocalekey='en_US', localesidkey='en_US',
			profileid = profile.Id, timezonesidkey='America/Los_Angeles', username='testtest01111@test.com'
		);
		insert user;
		
		List<Community_Group_Control__c> CommunityGroupControlList = new list <Community_Group_Control__c>();
		Community_Group_Control__c newtestgroup = new Community_Group_Control__c();
		newtestgroup.name = 'newtestgroup';
		newtestgroup.active__c = true;
		newtestgroup.automatic_Archive__c = true;
		newtestgroup.discoverable__c = true;
		newtestgroup.Type__c = 'Public';
		newtestgroup.Network__c = 'Internal';
		CommunityGroupControlList.add(newtestgroup);
		insert CommunityGroupControlList;
		CommunityGroupControlList[0].Chatter_Group_ID__c = 'TestGroupChatterId';
		update CommunityGroupControlList;
		
		List<Community_Group_Control__c> FollowGroupList = new list <Community_Group_Control__c>();
		Community_Group_Control__c followtestgroup = new Community_Group_Control__c();
		followtestgroup.name = 'followtestgroup';
		followtestgroup.active__c = true;
		followtestgroup.automatic_Archive__c = true;
		followtestgroup.discoverable__c = true;
		followtestgroup.Type__c = 'Public';
		followtestgroup.Network__c = 'Internal';
		FollowGroupList.add(followtestgroup);
		insert FollowGroupList;
		FollowGroupList[0].Chatter_Group_ID__c = 'TestFollChatterId';
		update FollowGroupList;
		
		List<entitySubscription> entitySubscriptionList = new list<entitySubscription>();
		entitySubscription subscript = new entitySubscription();
		subscript.SubscriberId = user.id;
		subscript.ParentId = CommunityGroupControlList[0].id;
		entitySubscriptionList.add(subscript);
		insert entitySubscriptionList;
		
		List<entitySubscription> entityFollowList = new list<entitySubscription>();
		entitySubscription Followsubscript = new entitySubscription();
		Followsubscript.SubscriberId = user.id;
		Followsubscript.ParentId = FollowGroupList[0].id;
		entityFollowList.add(Followsubscript);
		insert entityFollowList;
		
		CollaborationGroup CollGroup = new CollaborationGroup();
		CollGroup.Name = 'CollGroup';
		CollGroup.Description = 'TestDescription';
		CollGroup.InformationTitle = 'test';
		CollGroup.InformationBody = 'testtrst';
		CollGroup.CollaborationType = 'Public';
		CollGroup.NetworkId = CommunityGroupsBase.getCurrentCommunityId();
		insert CollGroup;
		
		
		
		
		
		
		
		CollaborationGroupMember CollGroupMember = new CollaborationGroupMember();
		CollGroupMember.NotificationFrequency = 'p';
		CollGroupMember.CollaborationGroupId = CollGroup.id;
		CollGroupMember.MemberId = user.id;		
		insert CollGroupMember;
		
		System.RunAs(user) {
			test.startTest();
			
			
			PageReference pr = new PageReference(Page.CommunityGroups.getUrl()+'?f=all_groups');
			Test.setCurrentPage(pr);
			CommunityGroupsController controller = new CommunityGroupsController();
			controller.initFromList();
			
			pr = new PageReference(Page.CommunityGroups.getUrl()+'?f=my_groups');
			Test.setCurrentPage(pr);
			controller = new CommunityGroupsController();
			controller.initFromList();
		
			pr = new PageReference(Page.CommunityGroups.getUrl()+'?f=recommended_groups');
			Test.setCurrentPage(pr);
			controller = new CommunityGroupsController();
			controller.initFromList();
		
			pr = new PageReference(Page.CommunityGroups.getUrl()+'?f=recommended_grou');
			Test.setCurrentPage(pr);
			controller = new CommunityGroupsController();
			controller.initFromList();

			controller.searchFromName();
			controller.goToCreateGroup();

			controller.currentFilter = 'TEST';
			controller.choiceFilter();

			controller.filterGroups();
			
			controller.currentFilter = 'All Groups';
			controller.filterGroups();
			
			controller.currentFilter = 'My Groups';
			controller.filterGroups();
			
			controller.currentFilter = 'Recommended Groups';
			controller.filterGroups();
			
			controller.followSobjectId = FollowGroupList[0].id;
			controller.follow();
			
			test.stopTest();
		}
		
	}


	static testMethod void CommunityGroupDetailPageController() {
		Profile profile = [SELECT Id, Name FROM profile WHERE name='System Administrator'];
		User user = new User(
			alias = 'tt01', email='testtest01@test.com', emailencodingkey='UTF-8',
			lastname='testtest01', languagelocalekey='en_US', localesidkey='en_US',
			profileid = profile.Id, timezonesidkey='America/Los_Angeles', username='testtest01111@test.com'
		);
		insert user;
		
		CollaborationGroup CollGroup = new CollaborationGroup();
		CollGroup.Name = 'CollGroup';
		CollGroup.Description = 'TestDescription';
		CollGroup.InformationTitle = 'test';
		CollGroup.InformationBody = 'testtrst';
		CollGroup.CollaborationType = 'Public';
		
		CollGroup.NetworkId = CommunityGroupsBase.getCurrentCommunityId();
		insert CollGroup;
		
		List<Community_Group_Control__c> CommunityGroupControlList = new list <Community_Group_Control__c>();
		Community_Group_Control__c newtestgroup = new Community_Group_Control__c();
		newtestgroup.name = 'newtestgroup';
		newtestgroup.active__c = true;
		newtestgroup.automatic_Archive__c = true;
		newtestgroup.discoverable__c = true;
		newtestgroup.Type__c = 'Public';
		newtestgroup.Network__c = 'Internal';
		CommunityGroupControlList.add(newtestgroup);
		insert CommunityGroupControlList;
		CommunityGroupControlList[0].Chatter_Group_ID__c = CollGroup.id;
		update CommunityGroupControlList;
		
		List<entitySubscription> entitySubscriptionList = new list<entitySubscription>();
		entitySubscription subscript = new entitySubscription();
		subscript.SubscriberId = user.id;
		subscript.ParentId = CommunityGroupControlList[0].id;
		entitySubscriptionList.add(subscript);
		insert entitySubscriptionList;
		


		CollaborationGroupMember CollGroupMember = new CollaborationGroupMember();
		CollGroupMember.NotificationFrequency = 'p';
		CollGroupMember.CollaborationGroupId = CollGroup.id;
		CollGroupMember.MemberId = user.id;		
		insert CollGroupMember;
		
		//communityGroupBase CGB = new communityGroupBase(CollGroup);
		//CGB.ChatterGroupDetail(CollGroup);
		//CommunityGroupsBase BaseController = new CommunityGroupsBase();
		//BaseController.ChatterGroupDetail CGD = new BaseController.ChatterGroupDetail(CollGroup);
		//insert CGD;
		
		
		
		//BaseController.ChatterGroupDetail CGD = new BaseController.ChatterGroupDetail(CollGroup);
		//insert CGD;
		
		
		System.RunAs(user) {
			test.startTest();
				
			PageReference pr = new PageReference(Page.CommunityGroupDetailPage.getUrl()+'?g='+CollGroup.id);
			Test.setCurrentPage(pr);
			CommunityGroupDetailPageController controller = new CommunityGroupDetailPageController();
			PageReference pr2 = new PageReference(Page.CommunityGroupDetailPage.getUrl()+'?gc='+CommunityGroupControlList[0].id);
			Test.setCurrentPage(pr2);
			CommunityGroupDetailPageController controller2 = new CommunityGroupDetailPageController();
			controller2.refresh();
			controller2.goToCreateEvent();
			
			test.stopTest();
		}
		
	}
	*/
	
	
	
}