src/objects/Community_Event_Tag__c.object
<CustomObject>
    <description>This object allows Tags and a Group to be associated to an Event record.</description>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated with this Event record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>Event Items Tagged</relationshipLabel>
        <relationshipName>Community_EventItems_Tagged</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Event Tag</label>
    <nameField>
        <displayFormat>CET-{yy}{mm}{0}</displayFormat>
        <label>Community Event Tag</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Event Tag</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Group_Control_Tag__c.object
<CustomObject>
    <description>This object allows tags to be associated with a Group Control record.</description>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <description>This defines the Tag that is being associated to the Group Control</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>Group Items Tagged</relationshipLabel>
        <relationshipName>Community_GroupItems_Tagged</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community Group Control Tag</label>
    <nameField>
        <displayFormat>CGCT-{yy}{mm}{0}</displayFormat>
        <label>Community Group Control Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Group Control Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_News_Tag__c.object
<CustomObject>
    <description>This object allows Tags to be associated to a Community News record.</description>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <description>Defines the tag that is being associated with the News record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>News Items Tagged</relationshipLabel>
        <relationshipName>Community_NewItems_Tagged</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community News Tag</label>
    <nameField>
        <displayFormat>CNT-{yy}{mm}{0}</displayFormat>
        <label>Community News Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_Tag__c.object
<CustomObject>
    <description>Define a library of Tags that will help categorize interests for the Community.  Tags can be associated to Community News, Events, Groups, and Contacts via separate junction objects.  This will allow the starter pack to recommend items to a Community user.</description>
    <fields>
        <fullName>Community_Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the Theme of the Community Tag.</description>
        <inlineHelpText>Represents the Theme of the Community Tag.</inlineHelpText>
        <label>Community Theme</label>
        <referenceTo>Community_Theme__c</referenceTo>
        <relationshipLabel>Community Tags</relationshipLabel>
        <relationshipName>Community_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tag_Theme_UniqueID__c</fullName>
        <description>Coming Soon.</description>
        <inlineHelpText>Coming Soon.</inlineHelpText>
        <label>Tag-Theme UniqueID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Theme_Type__c</fullName>
        <description>Represents the Theme Type of the Theme related to the Tag.</description>
        <formula>TEXT(Community_Theme__r.Theme_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Represents the Theme Type of the Theme related to the Tag.</inlineHelpText>
        <label>Theme Type</label>
        <type>Text</type>
    </fields>
    <label>Community Tag</label>
    <nameField>
        <label>Community Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Theme__c.object
<CustomObject>
    <description>Will be used to roll up Tags to a Theme.  Depending on attributes of the Theme, related Tags may be used in the Community Registration process or available to associate to Resources.</description>
    <fields>
        <fullName>Theme_Type__c</fullName>
        <description>determines if the theme will be available for resources, interests or system</description>
        <label>Theme Type</label>
        <picklist>
            <picklistValues>
                <fullName>Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Theme</label>
    <nameField>
        <label>Community Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommunityTagDisplayController.cls
/* 
 * Unity - Communities
 * 
 * Community is critical to the student experience--but building community is 
 * just plain hard. Built on Communities and designed specifically for higher ed, 
 * Unity is a powerful networking tool to help you generate engagement and 
 * connect your campus.
 * 
 * Copyright (C) 2015 Motivis Learning Systems Inc.
 * 
 * This program is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * 
 * To contact Motivis Learning Systems Inc.
 * 25 Pelham Road
 * Salem, NH 03790
 * unity@motivislearning.com
 */

public with sharing class CommunityTagDisplayController {
	public String objectId { get; set; }
	public String objectType { get; set; }
	public String filterName { get; set; }

	private static Map<System.Type,Integer> TYPE_MAP = new Map<System.Type,Integer> {
		Community_News_Tag__c.class => 1,
		Community_Group_Control_Tag__c.class => 2,
		Community_Event_Tag__c.class => 3
	};

	public Integer getMode() {
		Integer result = TYPE_MAP.get(Type.forName(objectType));
		return result == NULL ? 0 : result;
	}

	public List<Tag> getTags() {
		List<Tag> result = new List<Tag>();
		String queryObjectId = String.escapeSingleQuotes(objectId);
		String query = 'SELECT Id, Community_Tag__c FROM ' + objectType + ' WHERE ' + filterName + ' = :queryObjectId';
		query = CommunityUtils.systemTagFilter(' AND Community_Tag__r.Community_Theme__r.Theme_Type__c', query);
		List<SObject> sObjectList = Database.query(query);
		Set<String> tagIds = new Set<String>();
		for (SObject obj : sObjectList) {
			tagIds.add((String) obj.get('Community_Tag__c'));
		}
		for (Community_Tag__c t : [SELECT Id, Name, Tag_Theme_UniqueID__c, Community_Theme__r.Name FROM Community_Tag__c WHERE Id IN :tagIds]) {
			Tag tag = new Tag();
			tag.Name = t.Community_Theme__r.Name + ' > ' + t.Name;
			tag.Url = t.Id;
			result.add(tag);
		}
		return result;
	}

	public class Tag {
		public String Url { get; set; }
		public String Name { get; set; }
	}
}