src/objects/Community_Tag__c.object
<CustomObject>
    <description>Define a library of Tags that will help categorize interests for the Community.  Tags can be associated to Community News, Events, Groups, and Contacts via separate junction objects.  This will allow the starter pack to recommend items to a Community user.</description>
    <fields>
        <fullName>Community_Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the Theme of the Community Tag.</description>
        <inlineHelpText>Represents the Theme of the Community Tag.</inlineHelpText>
        <label>Community Theme</label>
        <referenceTo>Community_Theme__c</referenceTo>
        <relationshipLabel>Community Tags</relationshipLabel>
        <relationshipName>Community_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Icon_Style__c</fullName>
        <description>Describes the Icon style to be applied to these records in search results</description>
        <inlineHelpText>Describes the Icon style to be applied to these records in search results</inlineHelpText>
        <label>Icon Style</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theme_Type__c</fullName>
        <description>Represents the Theme Type of the Theme related to the Tag.</description>
        <formula>TEXT(Community_Theme__r.Theme_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Represents the Theme Type of the Theme related to the Tag.</inlineHelpText>
        <label>Theme Type</label>
        <type>Text</type>
    </fields>
    <label>Community Tag</label>
    <nameField>
        <label>Community Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Tag__c.object
    <fields>
        <fullName>Display_in_Wizard__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines whether tags within this Theme should be visible to users during the profile registration wizard for the Community.</description>
        <label>Display in Wizard</label>
        <type>Checkbox</type>
    </fields>

src/objects/Community_Theme__c.object
<CustomObject>
    <description>Will be used to roll up Tags to a Theme.  Depending on attributes of the Theme, related Tags may be used in the Community Registration process or available to associate to Resources.</description>
    <fields>
        <fullName>Icon_Color__c</fullName>
        <description>Choose from any of Font Awesome&apos;s Icon coloring classes</description>
        <inlineHelpText>Choose from any of Font Awesome&apos;s Icon coloring classes</inlineHelpText>
        <label>Icon Color</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon_Style__c</fullName>
        <description>Describes the Icon style to be applied to these records in search results</description>
        <inlineHelpText>Describes the Icon style to be applied to these records in search results</inlineHelpText>
        <label>Icon Style</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theme_Type__c</fullName>
        <description>determines if the theme will be available for resources, interests or system</description>
        <label>Theme Type</label>
        <picklist>
            <picklistValues>
                <fullName>Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Theme</label>
    <nameField>
        <label>Community Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Theme__c.object
    <fields>
        <fullName>Enable_in_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If TRUE, this theme will be presented to a Community user when registering for access to the community.</description>
        <label>Enable in Wizard</label>
        <type>Checkbox</type>
    </fields>

classes/CommunityDiscoverComponentController.cls
public with sharing class CommunityDiscoverComponentController {

    // COMMON VARIABLES
    public String tagId { get; set; }
    public List<Community_Theme__c> themes  { get; set; }
    public List<Community_Tag__c> allTags { get; set; }
    public Map<Id,List<Community_Tag__c>> themeTagsMap { get; set; }  //theme id to tag map
    public List<themeTagWapper> wrappedThemes { get; set; } 
    //CONTROLLER
    public CommunityDiscoverComponentController() {
        themeTagsMap = new Map<Id,List<Community_Tag__c>>();
        wrappedThemes = new List<themeTagWapper> ();
        
        //get all themes with their tags
        //List<theme> theThemes;
        themes = [SELECT Id, Theme_Type__c, Name, Icon_Style__c, Icon_Color__c, Enable_in_Wizard__c,
                    (Select Id, Display_in_Wizard__c, Name, Icon_Style__c FROM Community_Tags__r Order By Name)
                         From Community_Theme__c WHERE Enable_in_Wizard__c = true Order By Name];
                         
        //get all tags with theme names and child tags
        allTags = [
            SELECT Id, Community_Theme__c, Community_Theme__r.Icon_Color__c, Community_Theme__r.Name, Name, Icon_Style__c,
            (SELECT Id, Name FROM Events_Tag_Joins__r),
            (SELECT Id, Name FROM Community_Tag_Group_Control__r),
            (SELECT Id, Name FROM Community_Tag_News__r
                WHERE Community_News__r.Entry_Date__c >= TODAY
                AND Community_News__r.Expiration_Date__c <= TODAY),
            (SELECT Id, Name FROM Resource_Tag_Joins__r)
            FROM Community_Tag__c
        ];
        
        for (Community_Tag__c tag : allTags) {
            if(themeTagsMap.containsKey(tag.Community_Theme__c))
            {
                themeTagsMap.get(tag.Community_Theme__c).add(tag);
            } else {
                List<Community_Tag__c> temptagList = new List<Community_Tag__c>{tag};
                themeTagsMap.put(tag.Community_Theme__c,temptagList);
            }   
        }
        
        for(Community_Theme__c theme : themes) {
            if(themeTagsMap.containsKey(theme.Id)) {
                wrappedThemes.add(new themeTagWapper(theme,themeTagsMap.get(theme.Id) ));
            } else {
                wrappedThemes.add(new themeTagWapper(theme, new List<Community_Tag__c>() ));
            }   
        }
        
    }
    
    public class themeTagWapper {
        public Community_Theme__c theme {get; set;}
        public List<List<Community_Tag__c>> tagColumns {get; set;}
        public Map<Id,Integer> tagCounts { get; set;}
        
        public themeTagWapper(Community_Theme__c t, List<Community_Tag__c> tags) {
            theme = t;
            Integer breakpoint = 0;
            if(!tags.isEmpty()) {
                breakpoint =  tags.size()/3;    
            }
            tagColumns = new List<List<Community_Tag__c>>();
            for(Integer colCount = 0; colCount < 3; colCount++) {
                tagColumns.add( new List<Community_Tag__c>());
            }
            
            Integer tagCount = 0;
            Integer currentColumn = 0;
            tagCounts = new Map<Id,Integer>();
            for (Community_Tag__c tag : tags) {
                tagColumns[currentColumn].add(tag);
                if(tagCount == breakpoint)
                {
                    currentColumn++;
                    tagCount = 0;
                } else {
                    tagCount++;
                }
                
                tagCounts.put(tag.Id, tag.Events_Tag_Joins__r.size() + tag.Community_Tag_Group_Control__r.size() + tag.Community_Tag_News__r.size() + tag.Resource_Tag_Joins__r.size());
            }
            
        }
    }

}