src/objects/Community_Event_Tag__c.object
<CustomObject>
    <description>This object allows Tags and a Group to be associated to an Event record.</description>
    <fields>
        <fullName>Community_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated with this Event record.</description>
        <label>Community Event</label>
        <referenceTo>Community_Events__c</referenceTo>
        <relationshipLabel>Group &amp; Tags</relationshipLabel>
        <relationshipName>Events_Tag_Joins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Group_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows a Community Group to be associated with a Community Event.  Not mandatory.  Only used when joining a Community Event to a Chatter Group.</description>
        <label>Community Group Control</label>
        <referenceTo>Community_Group_Control__c</referenceTo>
        <relationshipLabel>Group Events</relationshipLabel>
        <relationshipName>Community_Event_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated with this Event record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>Event Items Tagged</relationshipLabel>
        <relationshipName>Community_EventItems_Tagged</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Event Tag</label>
    <nameField>
        <displayFormat>CET-{yy}{mm}{0}</displayFormat>
        <label>Community Event Tag</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Event Tag</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Events__c.object
<CustomObject>
    <description>Used to store Events in the Community.  Events may or may not be associated with a Group.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Provide a description of the Community Event details and RSVP instructions (if any)</description>
        <label>Description</label>
        <length>10000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Used to define a name for the event.  This field is mandatory.</description>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>Start Date/Time of the Community Event Record</description>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Community Event</label>
    <nameField>
        <displayFormat>EVENT.{yy}{mm}{0}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Group_Control__c.object
<CustomObject>
    <description>Represents the metadata associated with a Chatter Group that is created in the Community.  Is used to serve up the Group Manager feed separately from the Chatter Group Feed.</description>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This defines the 18-digit SFID of the related Chatter Group for the Group Control record.</description>
        <label>Chatter Group ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Defines a description for the Group Control which will also be related to the Chatter Group, if needed.</description>
        <inlineHelpText>Write a brief description of your group.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Represents the Type of Group that will be created in the system.</description>
        <inlineHelpText>If your group will be public, any user may join.  If your group will be private, members must be added by a group manager.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Group Control</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Group Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Group_Control__c.object
    <fields>
        <fullName>Image_Path__c</fullName>
        <label>Image Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Community_Tag__c.object
<CustomObject>
    <description>Define a library of Tags that will help categorize interests for the Community.  Tags can be associated to Community News, Events, Groups, and Contacts via separate junction objects.  This will allow the starter pack to recommend items to a Community user.</description>
    <label>Community Tag</label>
    <nameField>
        <label>Community Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CommunityGroupDetailPageController.cls
public with sharing class CommunityGroupDetailPageController extends CommunityGroupsBase {

	// -- common variables --
	public Community_Group_Control__c control { get;set; }
	public String description { get; set; }
	public String SitePrefix {
		get {
			if (this.SitePrefix == NULL) {
				this.SitePrefix = Site.getPathPrefix();
			}
			return this.SitePrefix;
		}
		private set;
	}
	public ChatterGroupDetail CurrentGroup { get; set; }
	
	public List<Community_Events__c> communityEventList { get;set; }
	public List<ContentDocumentLink> contentDocumentLinkList { get;set; }
	public Boolean isChatterGroup { get; set; }
	private final String CurrentCommunityId = getCurrentCommunityId();
	private final String CurrentGroupId = ApexPages.currentPage().getParameters().get('g');
	private final String CurrentGroupControlId = ApexPages.currentPage().getParameters().get('gc');
	
	public String CurrentUserId {
		get {
			return UserInfo.getUserId();
		}
		set;
	}

	public String subscriptionId {get; set;}
	public String followUserId {get; set;}

	// CONSTRUCTOR
	public CommunityGroupDetailPageController() {

		List<Community_Event_Tag__c> communityEventTagList = new List<Community_Event_Tag__c>();
		List<Community_Group_Control__c> communityGroupControllList = new List<Community_Group_Control__c>();
		List<String> communityEventTagIdList = new List<String>();
		List<String> communityGroupControlIdList = new List<String>();
		List<CollaborationGroup> collaborationGroupList = new List<CollaborationGroup>();
		List<CollaborationGroupMember> collaborationGroupMemberList = new List<CollaborationGroupMember>();
		List<EntitySubscription> subscriptionList = new List<EntitySubscription>();
		this.contentDocumentLinkList = new List<ContentDocumentLink>();
		this.communityEventList = new List<Community_Events__c>();
		this.isChatterGroup = false;

		if (CurrentGroupControlId != NULL) {
			communityGroupControllList = [
				SELECT Id, Name, Chatter_Group_ID__c, Description__c, Type__c, Image_Path__c, OwnerId
				FROM Community_Group_Control__c
				WHERE Id =: CurrentGroupControlId
				LIMIT 1
			];

			subscriptionList = [
				SELECT Id, ParentId
				FROM EntitySubscription
				WHERE ParentId = :CurrentGroupControlId
				AND SubscriberId = :UserInfo.getUserId()
				LIMIT 1
			];

		}

		if (!communityGroupControllList.isEmpty()) {
			if (communityGroupControllList[0].Chatter_Group_ID__c != NULL) {
				this.CurrentGroupId = communityGroupControllList[0].Chatter_Group_ID__c;
			}
			else {
				this.CurrentGroup = new ChatterGroupDetail(communityGroupControllList[0]);
				if (communityGroupControllList[0].OwnerId == UserInfo.getUserId()) {
					this.CurrentGroup.CurrentMemberRole = getMemberRole('Admin');
				}
				else if (!subscriptionList.isEmpty()) {
					this.CurrentGroup.CurrentMemberRole = getMemberRole('Standard');
				}
				else {
					this.CurrentGroup.CurrentMemberRole = getMemberRole('');
				}
//				this.CurrentGroup.Members = getMembersFromId(CurrentGroup.GroupId);
				this.contentDocumentLinkList = getContentDocumentLink(CurrentGroup.GroupId);
			}
		}

		if (this.CurrentGroupId != NULL) {
			collaborationGroupList = [
				SELECT CollaborationGroup.Id, CollaborationGroup.Name, CollaborationGroup.Description,
					CollaborationGroup.InformationTitle, CollaborationGroup.InformationBody,
					CollaborationGroup.SmallPhotoUrl, CollaborationGroup.FullPhotoUrl,
					CollaborationGroup.MemberCount, CollaborationGroup.LastFeedModifiedDate,
					CollaborationGroup.OwnerId, CollaborationGroup.NetworkId, CollaborationGroup.IsArchived,
					CollaborationGroup.CollaborationType, CollaborationGroup.CanHaveGuests,
					CollaborationGroup.Owner.Name, CollaborationGroup.Owner.FirstName,
					CollaborationGroup.Owner.LastName, CollaborationGroup.Owner.SmallPhotoUrl
				FROM CollaborationGroup
				WHERE Id =: this.CurrentGroupId
//				AND NetworkId =: this.CurrentCommunityId
				LIMIT 1
			];

			collaborationGroupMemberList = [
				SELECT MemberId, Id, CollaborationRole,
					CollaborationGroupId,
					CollaborationGroup.Id, CollaborationGroup.Name, CollaborationGroup.Description,
					CollaborationGroup.InformationTitle, CollaborationGroup.InformationBody,
					CollaborationGroup.SmallPhotoUrl, CollaborationGroup.FullPhotoUrl, CollaborationGroup.MemberCount,
					CollaborationGroup.LastFeedModifiedDate,
					CollaborationGroup.OwnerId, CollaborationGroup.NetworkId, CollaborationGroup.IsArchived,
					CollaborationGroup.CollaborationType, CollaborationGroup.CanHaveGuests,
					CollaborationGroup.Owner.Name, CollaborationGroup.Owner.FirstName,
					CollaborationGroup.Owner.LastName, CollaborationGroup.Owner.SmallPhotoUrl
				FROM CollaborationGroupMember
				WHERE CollaborationGroup.Id =: this.CurrentGroupId
				AND MemberId =: UserInfo.getUserId()
//				AND CollaborationGroup.NetworkId =: this.CurrentCommunityId
				LIMIT 1
			];

			communityGroupControllList = [
				SELECT Id, Chatter_Group_ID__c, Image_Path__c
				FROM Community_Group_Control__c
				WHERE Chatter_Group_ID__c =: CurrentGroupId
				LIMIT 1
			];
			this.contentDocumentLinkList = getContentDocumentLink(CurrentGroupId);
		}

		if (!collaborationGroupList.isEmpty()) {
			this.CurrentGroup = new ChatterGroupDetail(collaborationGroupList[0]);
			if (communityGroupControllList.size() > 0 && !String.isBlank(communityGroupControllList[0].Image_Path__c)) {
				this.CurrentGroup.GroupPhotoUrl = communityGroupControllList[0].Image_Path__c;
			}
			
			this.CurrentGroup.Members = getMembersFromId(CurrentGroup.GroupId);
			if (!collaborationGroupMemberList.isEmpty()) {
				this.CurrentGroup.CurrentMemberRole = getMemberRole(collaborationGroupMemberList[0].CollaborationRole);
			}
			else {
				this.CurrentGroup.CurrentMemberRole = getMemberRole('');
			}
			this.isChatterGroup = true;
		}

		if (!communityGroupControllList.isEmpty()) {
			for (Community_Group_Control__c Item : communityGroupControllList) {
				communityGroupControlIdList.add(Item.Id);
			}
			if (!communityGroupControlIdList.isEmpty()) {
				communityEventTagList = [
					SELECT Id, Community_Tag__c, Community_Event__c
					FROM Community_Event_Tag__c
					WHERE Community_Group_Control__c IN: communityGroupControlIdList
					ORDER BY CreatedDate DESC
				];
			}
		}

		if (!communityEventTagList.isEmpty()) {
			for (Community_Event_Tag__c communityEventItem : communityEventTagList) {
				communityEventTagIdList.add(communityEventItem.Community_Event__c);
			}
			if (!communityEventTagIdList.isEmpty()) {
				communityEventList = [
					SELECT Id, Name__c, Start__c
					FROM Community_Events__c
					WHERE Id IN: communityEventTagIdList
					AND Start__c > TODAY

				];
			}
		}

		if(control == null) {
			this.control = CommunityGroupManageController.pullGroupControlRecord(false);	
		}
		if(CurrentGroupControlId == null && control != null) {
			this.CurrentGroupControlId = (String)control.Id;
		}
		return;
	}

	//PUBLIC METHODS

	public PageReference refresh() {
		return NULL;
	}

	public void RefreshMembersInfo() {
		CurrentGroup.Members = getMembersFromId(CurrentGroup.GroupId);
	}
	
	public PageReference jointToGroup() {
		System.debug('CurrentGroupControlId:  ' + CurrentGroupControlId);
		System.debug('UserId: ' + UserInfo.getUserId());
		//ConnectApi.ChatterGroups.addMember(CurrentCommunityId, CurrentGroupId, UserInfo.getUserId());
		CommunityGroupManageController.membership(UserInfo.getUserId(), CurrentGroupControlId, '1'); //add member
		RefreshMembersInfo();
		//CurrentGroup.CurrentMemberRole = getMemberRole('Standard');
		return null;
	}

	public void leaveGroup() {
		System.debug('CurrentGroupControlId:  ' + CurrentGroupControlId);
		System.debug('UserId: ' + UserInfo.getUserId());
		//CollaborationGroupMember CurrentMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE CollaborationGroupId =: CurrentGroupId AND MemberId =: UserInfo.getUserId()];
		//ConnectApi.ChatterGroups.deleteMember(CurrentCommunityId, CurrentMember.Id);
		//CurrentGroup.CurrentMemberRole = getMemberRole('');
		CommunityGroupManageController.membership(UserInfo.getUserId(), CurrentGroupControlId, '2'); //remove member
		RefreshMembersInfo();
	}

	public void follow() {
		ConnectApi.Subscription currentSubsc = ConnectApi.ChatterUsers.follow(CurrentCommunityId, UserInfo.getUserId(), followUserId);
		for(ChatterGroupMember currentMember : CurrentGroup.Members) {
			if(currentMember.MemberId == followUserId) {
				currentMember.SubscriptionId = currentSubsc.Id;
				currentMember.MemberIsFollowing = true;
				break;
			}
		}
	}
	public PageReference unfollow() {
		ConnectApi.Chatter.deleteSubscription(CurrentCommunityId, subscriptionId);
		for(ChatterGroupMember currentMember : CurrentGroup.Members) {
			if(currentMember.SubscriptionId == subscriptionId) {
				currentMember.SubscriptionId = null;
				currentMember.MemberIsFollowing = false;
				break;
			}
		}
		return null;
	}

	public PageReference goToCreateEvent() {

		PageReference pr;

		if (!String.isBlank(CurrentGroupId)) {
			pr = new PageReference('/apex/CommunityEventEdit?g=' + CurrentGroup.GroupId
				+'&retURL=/apex/CommunityGroupDetailPage?g=' + CurrentGroupId
			);
		}
		else if (!String.isBlank(CurrentGroupControlId)) {
			pr = new PageReference('/apex/CommunityEventEdit?g=' + CurrentGroup.GroupId
				+'&retURL=/apex/CommunityGroupDetailPage?gc=' + CurrentGroupControlId
			);
		}

		return pr;
	}

	//PRIVATE METHODS
	//Get Group Files
	private List<ContentDocumentLink> getContentDocumentLink(String linkedEntityId) {

		List<ContentDocumentLink> result = new List<ContentDocumentLink>();

		if (!String.isBlank(linkedEntityId)) {
			result = [
				SELECT ContentDocument.Title, ContentDocument.Id
				FROM ContentDocumentLink
				WHERE LinkedEntityId =: linkedEntityId
			];
		}

		return result;
	}

	// Get Members
	private List<ChatterGroupMember> getMembersFromId(String groupId) {

		List<CollaborationGroupMember> groupMemberList = new List<CollaborationGroupMember>();
		List<ChatterGroupMember> result = new List<ChatterGroupMember>();

		if (!String.isBlank(groupId)) {
			groupMemberList = [
				SELECT MemberId, Id, CollaborationRole,
					CollaborationGroupId,
					CollaborationGroup.Id, CollaborationGroup.Name, CollaborationGroup.Description,
					CollaborationGroup.InformationTitle, CollaborationGroup.InformationBody,
					CollaborationGroup.SmallPhotoUrl, CollaborationGroup.FullPhotoUrl, CollaborationGroup.MemberCount,
					CollaborationGroup.LastFeedModifiedDate,
					CollaborationGroup.OwnerId, CollaborationGroup.NetworkId, CollaborationGroup.IsArchived,
					CollaborationGroup.CollaborationType, CollaborationGroup.CanHaveGuests,
					CollaborationGroup.Owner.Name, CollaborationGroup.Owner.FirstName,
					CollaborationGroup.Owner.LastName, CollaborationGroup.Owner.SmallPhotoUrl,
					CollaborationGroupMember.Member.FirstName, CollaborationGroupMember.Member.LastName,
					CollaborationGroupMember.Member.SmallPhotoUrl
				FROM CollaborationGroupMember
				WHERE CollaborationGroup.Id =: groupId
//				AND CollaborationGroup.NetworkId =: this.CurrentCommunityId
			];
		}

		if (!groupMemberList.isEmpty()) {
			List<ConnectApi.Subscription> following = ConnectApi.ChatterUsers.getFollowings(CurrentCommunityId, UserInfo.getUserId()).following;
			System.debug(following);
			Map<String, String> SubscriptionMap = new Map<String, String>();
			for(ConnectApi.Subscription currentSubsc : following) {
				SubscriptionMap.put(currentSubsc.subject.id, currentSubsc.id);
			}

			for (CollaborationGroupMember item : groupMemberList) {
				ChatterGroupMember Member = new ChatterGroupMember(item);

				Boolean isFollowing = (item.MemberId != UserInfo.getUserId()) ? SubscriptionMap.containsKey(item.MemberId) : null;
				Member.MemberIsFollowing = isFollowing;

				String SubscriptionId = (SubscriptionMap.containsKey(item.MemberId)) ? SubscriptionMap.get(item.MemberId) : '';
				Member.SubscriptionId = SubscriptionId;
				
				result.add(Member);
			}
		}

		return result;
	}

}