src/objects/Community_Admins__c.object
<CustomObject>
    <description>Used to store data values that are necessary for some Community features such as Terms and Conditions</description>
    <fields>
        <fullName>Terms_Body__c</fullName>
        <description>Represents the Body of the Terms that will be displayed in the Community Portal when published.</description>
        <inlineHelpText>Represents the Body of the Terms that will be displayed in the Community Portal when published.</inlineHelpText>
        <label>Terms Body</label>
        <length>131000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Terms_Published_Date__c</fullName>
        <description>Represents the Date/Time when the Terms records was published.</description>
        <inlineHelpText>Represents the Date/Time when the Terms records was published.</inlineHelpText>
        <label>Terms Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Terms_Status__c</fullName>
        <description>Represents the Status of the Terms &amp; Conditions from Writing to Publishing.</description>
        <inlineHelpText>Represents the Status of the Terms &amp; Conditions from Writing to Publishing.</inlineHelpText>
        <label>Terms Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Process</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Admin</label>
    <nameField>
        <displayFormat>CA.{yy}{mm}{0}</displayFormat>
        <label>Community Admin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Admin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Group_Control__c.object
<CustomObject>
    <description>Represents the metadata associated with a Chatter Group that is created in the Community.  Is used to serve up the Group Manager feed separately from the Chatter Group Feed.</description>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This defines the 18-digit SFID of the related Chatter Group for the Group Control record.</description>
        <label>Chatter Group ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the Status of the Group Control record.</description>
        <inlineHelpText>Represents the Status of the Group Control record.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>T_C_Accepted_Date__c</fullName>
        <description>Indicates the Date/Time when the Terms &amp; Conditions page was accepted by the User.</description>
        <inlineHelpText>Indicates the Date/Time when the Terms &amp; Conditions page was accepted by the User.</inlineHelpText>
        <label>T&amp;C Accepted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>T_C_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates the Date/Time when the Terms &amp; Conditions page was accepted by the User.</description>
        <inlineHelpText>Indicates the Date/Time when the Terms &amp; Conditions page was accepted by the User.</inlineHelpText>
        <label>T&amp;C Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the Group Terms &amp; Conditions record the User accepted.</description>
        <inlineHelpText>Represents the Group Terms &amp; Conditions record the User accepted.</inlineHelpText>
        <label>Terms</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Community_Admins__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Group Terms</value>
            </filterItems>
            <infoMessage>You can only add a record that has a Record Type of Group Terms.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Community_Admins__c</referenceTo>
        <relationshipLabel>Community Group Controls</relationshipLabel>
        <relationshipName>Community_Group_Controls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Group Control</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Group Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Group_Control_Tag__c.object
<CustomObject>
    <description>This object allows tags to be associated with a Group Control record.</description>
    <fields>
        <fullName>Group_Control__c</fullName>
        <description>This field defines the Group that tags will be associated with</description>
        <label>Group Control</label>
        <referenceTo>Community_Group_Control__c</referenceTo>
        <relationshipLabel>Group Tags</relationshipLabel>
        <relationshipName>Community_Group_Tags</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community Group Control Tag</label>
    <nameField>
        <displayFormat>CGCT-{yy}{mm}{0}</displayFormat>
        <label>Community Group Control Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Group Control Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>All custom settings for the Community will be stored within this object.</description>
    <fields>
        <fullName>Create_Group_Disable_Terms__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When selected, the Terms page will be disabled during the Create Group process.</description>
        <inlineHelpText>When selected, the Terms page will be disabled during the Create Group process.</inlineHelpText>
        <label>Create Group Disable Terms</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Group_Max_Tags__c</fullName>
        <description>The number provided in this box indicates the max number of Tags a User can apply to a Group.  When NULL, the User can apply as many tags allowed.</description>
        <inlineHelpText>The number provided in this box indicates the max number of Tags a User can apply to a Group.  When NULL, the User can apply as many tags allowed.</inlineHelpText>
        <label>Create Group Max Tags</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Create_Group_Require_Tags__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When selected, the User will be required to select at least 1 Tag during the Create Group creation.</description>
        <inlineHelpText>When selected, the User will be required to select at least 1 Tag during the Create Group creation.</inlineHelpText>
        <label>Create Group Require Tags</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/classes/CommunityGroupCreateController.cls
/*
 * Unity - Communities
 *
 * Community is critical to the student experience--but building community is
 * just plain hard. Built on Communities and designed specifically for higher ed,
 * Unity is a powerful networking tool to help you generate engagement and
 * connect your campus.
 *
 * Copyright (C) 2015 Motivis Learning Systems Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * To contact Motivis Learning Systems Inc.
 * 25 Pelham Road
 * Salem, NH 03790
 * unity@motivislearning.com
 */

public with sharing class CommunityGroupCreateController {

	public Community_Group_Control__c currentGroup { get; set; }
	public Blob imageBody { get; set; }
	public String imageFileName { get; set; }
	public String imageContentType { get; set; }
	public Integer step { get; set; }

	public CommunityFieldLayout flayout { get;set; }

	// photo positions vars
	public String photoContentType { get; set; }
	public String blobImageData { get; set; }
	public String cropXCr { get; set; }
	public String cropYCr { get; set; }
	public String cropSizeCr { get; set; }

	public String arhivingValue { get; set; }

	private final String TAGS_INPUT_NAME = 'tags';

	public CommunityGroupCreateController(ApexPages.StandardController stdController) {
		currentGroup = (Community_Group_Control__c)stdController.getRecord();
		if(currentGroup.Id == NULL) arhivingValue = 'true';
	}

	private Map<String, String> pageParams {
		get {
			return  ApexPages.currentPage().getParameters();
		}
		set;
	}

	public PageReference initFromView() {
		PageReference pageRef = CommunityUtils.checkRedirectToStandardView(currentGroup.Id);
		if (pageRef == NULL) {
			if (!SObjectType.Community_Group_Control__c.isAccessible()) CommunityAccess.ThrowAccessException(SObjectType.Community_Group_Control__c);
			currentGroup = [SELECT Id, Chatter_Group_Id__c FROM Community_Group_Control__c WHERE Id = :currentGroup.Id LIMIT 1];
			pageRef = Page.CommunityGroupManager;
			pageRef.getParameters().put('gr', currentGroup.Chatter_Group_ID__c);
		}
		return pageRef;
	}

	public void initFromCreate() {
		Set<String> availableSteps = new Set<String> {'2','3','4'};
		//Map<String, String> pageParams = ApexPages.currentPage().getParameters();
		String stepStr = (String.isNotBlank(pageParams.get('step')) && availableSteps.contains(pageParams.get('step'))) ? pageParams.get('step') : '1';
		step = Integer.valueOf(stepStr);
		// prepare field layout
		List<String> fieldList = new List<String> {
			'Id', 'Name', 'Status__c', 'Chatter_Group_ID__c', 'T_C_Accepted__c', 'T_C_Accepted_Date__c', 'Terms__c'
		};
		CommunityFieldLayout flt = new CommunityFieldLayout(
			currentGroup.Id,
			SObjectType.Community_Group_Control__c.FieldSets.CreateGroup,
			SObjectType.Community_Group_Control__c,
			fieldList,
			CommunityUtils.getPackagePrefix()
		);
		if (currentGroup.Id != NULL) {
			currentGroup = (Community_Group_Control__c)flt.getRecord();
		}
		if (!CommunityUtils.canCreateGroup() || (currentGroup.Id != NULL && currentGroup.Status__c != 'Pending')) {
			step = 0;
		}
		if (step == 1) {
			flayout = flt;
			List<CommunityFieldLayout.Field> fieldsWOname = new List<CommunityFieldLayout.Field>();
			for (CommunityFieldLayout.Field ff : flayout.flds) {
				if (ff.name != 'Name') {
					fieldsWOname.add(ff);
				}
			}
			flayout.flds = fieldsWOname;
		}
	}

	public String getEmptyGroupPhotoUrl() {
		return CommunityUtils.checkUrl('/profilephoto/0F9/F');
	}

	public PageReference doSubmit() {
		PageReference pr;
		try {
			if (step == 1) {
				currentGroup.Status__c = 'Pending';
				currentGroup.Automatic_Archiving__c = arhivingValue.equals('true') ? true : false;
				//upsert currentGroup;
				CommunityAccess.UpsertWithoutSharing(
					currentGroup,
					'CommunityGroupCreateController.cls [doSubmit]',
					new List<Schema.DescribeFieldResult> {
						Community_Group_Control__c.Name.getDescribe(),
						Community_Group_Control__c.Status__c.getDescribe(),
						Community_Group_Control__c.Chatter_Group_ID__c.getDescribe()
					}
				);
				pr = Page.CommunityGroupCreate;
				if (!SObjectType.Community_Group_Control__c.isAccessible()) CommunityAccess.ThrowAccessException(SObjectType.Community_Group_Control__c);
				currentGroup = [SELECT Id, Chatter_Group_ID__c FROM Community_Group_Control__c WHERE Id =:currentGroup.Id];
				pr.getParameters().put('step', String.isBlank(currentGroup.Chatter_Group_ID__c) ? '3' : '2');
			}
			else if (step == 2) {
				if (String.isNotBlank(blobImageData)) {
					Blob bl;				
					bl = EncodingUtil.base64Decode(blobImageData);
				    ConnectApi.PhotoInput pi = new ConnectApi.PhotoInput();
				    pi.cropX = Integer.valueOf(cropXCr);
				    pi.cropY = Integer.valueOf(cropYCr);
				    pi.cropSize = Integer.valueOf(cropSizeCr)-1;
					ConnectApi.Photo groupPhoto = ConnectApi.ChatterGroups.setPhotoWithAttributes(
					    Network.getNetworkId(), 
					    currentGroup.Chatter_Group_ID__c,
					    pi,
					    new ConnectApi.BinaryInput(bl, photoContentType, 'image.jpg')
					    );
					//update currentGroup;
					CommunityAccess.UpdateWithoutSharing(
						currentGroup,
						'CommunityGroupCreateController.cls [doSubmit]',
						new List<Schema.DescribeFieldResult> {
							Community_Group_Control__c.Chatter_Group_ID__c.getDescribe()
						}
					);
				}
				pr = Page.CommunityGroupCreate;
				pr.getParameters().put('step', '3');
			}
			else if (step == 3) {
				String tagsIdsString = ApexPages.currentPage().getParameters().get(this.TAGS_INPUT_NAME);
				CommunityTagSelectorController ctsc = new CommunityTagSelectorController();
				ctsc.objectId = this.currentGroup.Id;
				ctsc.objectType = Community_Group_Control_Tag__c.getSObjectType().getDescribe().getName();
				ctsc.filterName = Community_Group_Control_Tag__c.Group_Control__c.getDescribe().getName();
				ctsc.saveTags(tagsIdsString);

				Community_Settings__c cs = Community_Settings__c.getInstance();
				if (cs != NULL && cs.Create_Group_Disable_Terms__c == true) {
					pr = Page.CommunityGroupManager;
					pr.getParameters().put('gc', currentGroup.Id);
					currentGroup.Status__c = 'Approved';
					//update currentGroup;
					CommunityAccess.UpdateWithoutSharing(
						currentGroup,
						'CommunityGroupCreateController.cls [doSubmit]',
						new List<Schema.DescribeFieldResult> {
							Community_Group_Control__c.Status__c.getDescribe()
						}
					);
				}
				else {
					pr = Page.CommunityGroupCreate;
					pr.getParameters().put('step', '4');
				}
			}
			else if (step == 4) {
				pr = Page.CommunityGroupManager;
				pr.getParameters().put('gc', currentGroup.Id);
				currentGroup.T_C_Accepted_Date__c = Datetime.Now();
				if (!SObjectType.Community_Admins__c.isAccessible()) CommunityAccess.ThrowAccessException(SObjectType.Community_Admins__c);
				List<Community_Admins__c> caList = [
					SELECT Id FROM Community_Admins__c
					WHERE Terms_Status__c = 'Published' AND RecordType.Name = 'Group Terms'
					ORDER BY CreatedDate DESC LIMIT 1
				];
				if (caList != NULL && caList.size() > 0) {
					currentGroup.Terms__c = caList[0].Id;
				}
				currentGroup.Status__c = 'Approved';
				//update currentGroup;
				CommunityAccess.UpdateWithoutSharing(
					currentGroup,
					'CommunityGroupCreateController.cls [doSubmit]',
					new List<Schema.DescribeFieldResult> {
						Community_Group_Control__c.Status__c.getDescribe()
					}
				);
			}
			pr.getParameters().put('id', currentGroup.Id);
			pr.setRedirect(true);
		}
		catch (Exception e) {
			ApexPages.addMessages(e);
		}
		return pr;
	}

	public String headerText {
		get {
			String result = Label.BTN_Create_Group;
			if (step == 1) {
				result += ' (' + Label.LBL_CreateGroup_Details + ')';
			}
			else if (step == 2) {
				result += ' (' + Label.LBL_CreateGroup_PictureUpload + ')';
			}
			else if (step == 3) {
				result += ' (' + Label.LBL_Select_Tags + ')';
			}
			else if (step == 4) {
				result += ' (' + Label.LBL_TermsAndConditions + ')';
			}
			return result;
		}
	}

	public Boolean getDisabledNext() {
		Community_Settings__c cs = Community_Settings__c.getInstance();
		return step == 1 || step == 4 || (step == 3 && cs != NULL && cs.Create_Group_Require_Tags__c == true);
	}

	public Integer getTagsCount() {
		Community_Settings__c cs = Community_Settings__c.getInstance();
		return (step == 3 && cs != NULL && cs.Create_Group_Max_Tags__c != NULL)
				? Integer.valueOf(cs.Create_Group_Max_Tags__c)
				: -1;
	}

	public Community_Admins__c getTermsAndConditions() {
		List<Community_Admins__c> caList;
		if (step == 4) {
			if (!SObjectType.Community_Admins__c.isAccessible()) CommunityAccess.ThrowAccessException(SObjectType.Community_Admins__c);
			caList = [
				SELECT Terms_Body__c FROM Community_Admins__c
				WHERE Terms_Status__c = 'Published' AND RecordType.Name = 'Group Terms'
				ORDER BY Terms_Published_Date__c DESC LIMIT 1
			];
		}
		return caList != NULL && caList.size() > 0 ? caList[0] : new Community_Admins__c(Terms_Body__c = '');
	}

	public PageReference cancel() {
		if (String.isNotBlank(currentGroup.Chatter_Group_ID__c)) {
			List<CollaborationGroup> cgToDelete = [SELECT Id FROM CollaborationGroup WHERE Id = :currentGroup.Chatter_Group_ID__c];
			if (cgToDelete.size() > 0) {
				//delete cgToDelete;
				CommunityAccess.DeleteWithoutSharing(
					cgToDelete,
					'CommunityGroupCreateController.cls [cancel]'
				);
			}
		}
		//delete currentGroup;
		CommunityAccess.DeleteWithoutSharing(
			currentGroup,
			'CommunityGroupCreateController.cls [cancel]'
		);
		PageReference pr = Page.CommunityGroups;
		pr.getParameters().put('f', 'all_groups');
		pr.setRedirect(true);
		return pr;
	}

	public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
		options.add(new SelectOption('true', Label.LBL_Archive_90_days));
        options.add(new SelectOption('false', Label.LBL_Dont_auto_archive));
        return options;
    }

	@RemoteAction
	public static Boolean checkAvailability(String nameToCheck) {
		String queryNameToCheck = String.escapeSingleQuotes(nameToCheck);
		if (!SObjectType.Community_Group_Control__c.isAccessible()) CommunityAccess.ThrowAccessException(SObjectType.Community_Group_Control__c);
		List<Community_Group_Control__c> matchedGroups = [SELECT Id FROM Community_Group_Control__c WHERE Name = :queryNameToCheck];
		List<CollaborationGroup> matchedChatterGroups = [SELECT Id FROM CollaborationGroup WHERE Name = :queryNameToCheck];
		return matchedGroups.isEmpty() && matchedChatterGroups.isEmpty();
	}
}