src/objects/Community_News__c.object
<CustomObject>
    <description>This object stores News stories (links or text content) that are published to the Community.</description>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <description>Represents the Date/Time when the News Article will be posted in the Community Portal.  This will be based on the Organizations Time Zone in Salesforce.</description>
        <inlineHelpText>Represents the Date/Time when the News Article will be posted in the Community Portal.  This will be based on the Organizations Time Zone in Salesforce.</inlineHelpText>
        <label>Entry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Represents the Date/Time when the News Article will be removed from the Community Portal.  The time will be based on the Organizations Time Zone in Salesforce.</description>
        <inlineHelpText>Represents the Date/Time when the News Article will be removed from the Community Portal.  The time will be based on the Organizations Time Zone in Salesforce.</inlineHelpText>
        <label>Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Feature_on_Home_Page_Slot__c</fullName>
        <description>Use this field if this record will be featured on the Home Page.  The selected value will determine the order of this item in the Campus Updates section.</description>
        <label>Feature on Home Page - Slot #</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Image_Path__c</fullName>
        <description>Indicates the path where the image is stored and pulled from to display in the Community Portal.</description>
        <inlineHelpText>Indicates the path where the image is stored and pulled from to display in the Community Portal.</inlineHelpText>
        <label>Image Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make_Entry_Sticky__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When selected, the News Article will always appear at the top of the News Article Listed.  If multiple active Sticky, articles will be listed in Descending Order by Entry Date field.</description>
        <inlineHelpText>When selected, the News Article will always appear at the top of the News Article Listed.  If multiple active Sticky, articles will be listed in Descending Order by Entry Date field.</inlineHelpText>
        <label>Make Entry Sticky</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Teaser__c</fullName>
        <description>Represents a short description of the News article that will be posted in the Community Portal.</description>
        <inlineHelpText>Represents a short description of the News article that will be posted in the Community Portal.</inlineHelpText>
        <label>Teaser</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Represents the title of the news that will be displayed in the Community Portal.</description>
        <inlineHelpText>Represents the title of the news that will be displayed in the Community Portal.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Community News</label>
    <nameField>
        <displayFormat>News.{yy}{mm}{0}</displayFormat>
        <label>News</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_News_Tag__c.object
<CustomObject>
    <description>This object allows Tags to be associated to a Community News record.</description>
    <fields>
        <fullName>Community_News__c</fullName>
        <description>Allows tags to be associated with this Community News record.</description>
        <label>Community News</label>
        <referenceTo>Community_News__c</referenceTo>
        <relationshipLabel>News Tags</relationshipLabel>
        <relationshipName>Community_News_Tag</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <description>Defines the tag that is being associated with the News record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>News Items Tagged</relationshipLabel>
        <relationshipName>Community_NewItems_Tagged</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community News Tag</label>
    <nameField>
        <displayFormat>CNT-{yy}{mm}{0}</displayFormat>
        <label>Community News Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_Tag__c.object
<CustomObject>
    <description>Define a library of Tags that will help categorize interests for the Community.  Tags can be associated to Community News, Events, Groups, and Contacts via separate junction objects.  This will allow the starter pack to recommend items to a Community user.</description>
    <fields>
        <fullName>Community_Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the Theme of the Community Tag.</description>
        <inlineHelpText>Represents the Theme of the Community Tag.</inlineHelpText>
        <label>Community Theme</label>
        <referenceTo>Community_Theme__c</referenceTo>
        <relationshipLabel>Community Tags</relationshipLabel>
        <relationshipName>Community_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Theme_Type__c</fullName>
        <description>Represents the Theme Type of the Theme related to the Tag.</description>
        <formula>TEXT(Community_Theme__r.Theme_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Represents the Theme Type of the Theme related to the Tag.</inlineHelpText>
        <label>Theme Type</label>
        <type>Text</type>
    </fields>
    <label>Community Tag</label>
    <nameField>
        <label>Community Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Tag__c.object
    <fields>
        <fullName>Display_in_Wizard__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines whether tags within this Theme should be visible to users during the profile registration wizard for the Community.</description>
        <label>Display in Wizard</label>
        <type>Checkbox</type>
    </fields>

src/objects/Community_Theme__c.object
<CustomObject>
    <description>Will be used to roll up Tags to a Theme.  Depending on attributes of the Theme, related Tags may be used in the Community Registration process or available to associate to Resources.</description>
    <fields>
        <fullName>Theme_Type__c</fullName>
        <description>determines if the theme will be available for resources, interests or system</description>
        <label>Theme Type</label>
        <picklist>
            <picklistValues>
                <fullName>Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Theme</label>
    <nameField>
        <label>Community Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CommunityHomeComponentController.cls
public with sharing class CommunityHomeComponentController {
	/* -- Campus Section Component -- */
	public List<Community_News__c> getCampusNews() {
		return [
			SELECT Id, Title__c, Teaser__c, Image_Path__c
			FROM Community_News__c
			WHERE Feature_on_Home_Page_Slot__c != NULL AND Expiration_Date__c > TODAY
			ORDER BY Feature_on_Home_Page_Slot__c ASC NULLS LAST
			LIMIT 3
				];
	}
	/* !-- Campus Section Component -- */

	/* -- My News Component -- */
	public List<News> getMyNews() {
		List<Community_News__c> cnList = [
			SELECT Id, Title__c, Teaser__c, Image_Path__c, Entry_Date__c
			FROM Community_News__c
			WHERE Entry_Date__c <= TODAY AND Expiration_Date__c > TODAY
			AND Make_Entry_Sticky__c = true
			ORDER BY Make_Entry_Sticky__c, Entry_Date__c DESC LIMIT 2
				];
		List<News> resultList = new List<News>();
		if (cnList.size() > 0) {
			Set<Id> newsIds = new Set<Id>();
			for (Community_News__c cnItem : cnList) {
				newsIds.add(cnItem.Id);
			}
			Map<Id, Community_Tag__c> newsTagMap = new Map<Id, Community_Tag__c>();
			for (Community_News_Tag__c cntItem : [
				SELECT Community_News__c, Community_Tag__c, Community_Tag__r.Community_Theme__c, Community_Tag__r.Community_Theme__r.Theme_Type__c,
					Community_Tag__r.Name
				FROM Community_News_Tag__c
				WHERE Community_News__c IN :newsIds
				ORDER BY Community_Tag__r.Display_In_Wizard__c, Community_Tag__r.Name ASC
					]) {
				if (!newsTagMap.containsKey(cntItem.Community_News__c)) {
					newsTagMap.put(cntItem.Community_News__c, cntItem.Community_Tag__r);
				}
			}
			for (Community_News__c cnItem2 : cnList) {
				resultList.add(new News(cnItem2, newsTagMap.get(cnItem2.Id)));
			}
		}
		return resultList;
	}
	/* !-- My News Component -- */

	/* -- Wrapper -- */
	private static final Map<String,String> TAG_STYLE = new Map<String,String> {
		'default' => 'label-blue', 'Interest' => 'label-green', 'Resource' => 'label-sea'
	};
	public class News {
		public String id { get;set; }
		public String title { get;set; }
		public String imageUrl { get;set; }
		public String teaser { get;set; }
		public String entryDate { get;set; }
		public Boolean useTag { get;set; }
		public String tagStyle { get;set; }
		public String tag { get;set; }

		public News(Community_News__c incn) {
			id = incn.Id;
			title = incn.Title__c;
			imageUrl = incn.Image_Path__c;
			teaser = incn.Teaser__c;
		}

		public News(Community_News__c incn, Community_Tag__c intag) {
			id = incn.Id;
			title = incn.Title__c;
			imageUrl = incn.Image_Path__c;
			teaser = incn.Teaser__c;
			entryDate = incn.Entry_Date__c.format('MMMMM, d, yyyy');
			useTag = intag != NULL;
			if (useTag) {
				tag = intag.Name;
				String typeKey = (intag.Community_Theme__c == NULL || String.isBlank(intag.Community_Theme__r.Theme_Type__c)) ? 'default' : intag.Community_Theme__r.Theme_Type__c;
				tagStyle = TAG_STYLE.get(typeKey);
			}
		}
	}
	/* !-- Wrapper -- */
}