src/objects/Community_Event_Tag__c.object
<CustomObject>
    <description>This object allows Tags and a Group to be associated to an Event record.</description>
    <fields>
        <fullName>Community_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated with this Event record.</description>
        <label>Community Event</label>
        <referenceTo>Community_Events__c</referenceTo>
        <relationshipLabel>Group &amp; Tags</relationshipLabel>
        <relationshipName>Events_Tag_Joins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Group_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows a Community Group to be associated with a Community Event.  Not mandatory.  Only used when joining a Community Event to a Chatter Group.</description>
        <label>Community Group Control</label>
        <referenceTo>Community_Group_Control__c</referenceTo>
        <relationshipLabel>Group Events</relationshipLabel>
        <relationshipName>Community_Event_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated with this Event record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>Event Items Tagged</relationshipLabel>
        <relationshipName>Community_EventItems_Tagged</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Event Tag</label>
    <nameField>
        <displayFormat>CET-{yy}{mm}{0}</displayFormat>
        <label>Community Event Tag</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Event Tag</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Events__c.object
<CustomObject>
    <description>Used to store Events in the Community.  Events may or may not be associated with a Group.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Provide a description of the Community Event details and RSVP instructions (if any)</description>
        <label>Description</label>
        <length>10000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Used to define a name for the event.  This field is mandatory.</description>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>Start Date/Time of the Community Event Record</description>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Teaser__c</fullName>
        <description>Provide a teaser description for the Event, to be displayed on the Event Listing page within the Community.</description>
        <inlineHelpText>The Teaser is shown on the Event Listing page for Events that are flagged as Public.</inlineHelpText>
        <label>Teaser</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <label>Community Event</label>
    <nameField>
        <displayFormat>EVENT.{yy}{mm}{0}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Group_Control__c.object
<CustomObject>
    <description>Represents the metadata associated with a Chatter Group that is created in the Community.  Is used to serve up the Group Manager feed separately from the Chatter Group Feed.</description>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This defines the 18-digit SFID of the related Chatter Group for the Group Control record.</description>
        <label>Chatter Group ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Defines a description for the Group Control which will also be related to the Chatter Group, if needed.</description>
        <inlineHelpText>Write a brief description of your group.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Represents the Type of Group that will be created in the system.</description>
        <inlineHelpText>If your group will be public, any user may join.  If your group will be private, members must be added by a group manager.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Group Control</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Group Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Group_Control__c.object
    <fields>
        <fullName>Image_Path__c</fullName>
        <label>Image Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Community_Group_Control_Tag__c.object
<CustomObject>
    <description>This object allows tags to be associated with a Group Control record.</description>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <description>This defines the Tag that is being associated to the Group Control</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>Group Items Tagged</relationshipLabel>
        <relationshipName>Community_GroupItems_Tagged</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group_Control__c</fullName>
        <description>This field defines the Group that tags will be associated with</description>
        <label>Group Control</label>
        <referenceTo>Community_Group_Control__c</referenceTo>
        <relationshipLabel>Group Tags</relationshipLabel>
        <relationshipName>Community_Group_Tags</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community Group Control Tag</label>
    <nameField>
        <displayFormat>CGCT-{yy}{mm}{0}</displayFormat>
        <label>Community Group Control Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Group Control Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_News__c.object
<CustomObject>
    <description>This object stores News stories (links or text content) that are published to the Community.</description>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <description>Represents the Date/Time when the News Article will be posted in the Community Portal.  This will be based on the Organizations Time Zone in Salesforce.</description>
        <inlineHelpText>Represents the Date/Time when the News Article will be posted in the Community Portal.  This will be based on the Organizations Time Zone in Salesforce.</inlineHelpText>
        <label>Entry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Represents the Date/Time when the News Article will be removed from the Community Portal.  The time will be based on the Organizations Time Zone in Salesforce.</description>
        <inlineHelpText>Represents the Date/Time when the News Article will be removed from the Community Portal.  The time will be based on the Organizations Time Zone in Salesforce.</inlineHelpText>
        <label>Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Image_Path__c</fullName>
        <description>Indicates the path where the image is stored and pulled from to display in the Community Portal.</description>
        <inlineHelpText>Indicates the path where the image is stored and pulled from to display in the Community Portal.</inlineHelpText>
        <label>Image Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teaser__c</fullName>
        <description>Represents a short description of the News article that will be posted in the Community Portal.</description>
        <inlineHelpText>Represents a short description of the News article that will be posted in the Community Portal.</inlineHelpText>
        <label>Teaser</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Represents the title of the news that will be displayed in the Community Portal.</description>
        <inlineHelpText>Represents the title of the news that will be displayed in the Community Portal.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates the type of news that is being added.  Internal represents a news article pasted into Salesforce and an External would be a link to an article posted somewhere on the internet.</description>
        <inlineHelpText>Indicates the type of news that is being added.  Internal represents a news article pasted into Salesforce and an External would be a link to an article posted somewhere on the internet.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community News</label>
    <nameField>
        <displayFormat>News.{yy}{mm}{0}</displayFormat>
        <label>News</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_News_Tag__c.object
<CustomObject>
    <description>This object allows Tags to be associated to a Community News record.</description>
    <fields>
        <fullName>Community_News__c</fullName>
        <description>Allows tags to be associated with this Community News record.</description>
        <label>Community News</label>
        <referenceTo>Community_News__c</referenceTo>
        <relationshipLabel>News Tags</relationshipLabel>
        <relationshipName>Community_News_Tag</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <description>Defines the tag that is being associated with the News record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>News Items Tagged</relationshipLabel>
        <relationshipName>Community_NewItems_Tagged</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community News Tag</label>
    <nameField>
        <displayFormat>CNT-{yy}{mm}{0}</displayFormat>
        <label>Community News Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_Resource__c.object
<CustomObject>
    <description>This object is used to store links to external systems and resource documents.  Resources will be organized by Themes and Tags where Theme.Type = Resource</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Represents a description of the Resource that is presented in the Community.</description>
        <inlineHelpText>Represents a description of the Resource that is presented in the Community.</inlineHelpText>
        <label>Description</label>
        <length>15000</length>
        <type>Html</type>
    </fields>
    <label>Community Resource</label>
    <nameField>
        <label>Resource Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Tag__c.object
<CustomObject>
    <description>Define a library of Tags that will help categorize interests for the Community.  Tags can be associated to Community News, Events, Groups, and Contacts via separate junction objects.  This will allow the starter pack to recommend items to a Community user.</description>
    <fields>
        <fullName>Community_Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the Theme of the Community Tag.</description>
        <inlineHelpText>Represents the Theme of the Community Tag.</inlineHelpText>
        <label>Community Theme</label>
        <referenceTo>Community_Theme__c</referenceTo>
        <relationshipLabel>Community Tags</relationshipLabel>
        <relationshipName>Community_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Icon_Style__c</fullName>
        <description>Describes the Icon style to be applied to these records in search results</description>
        <inlineHelpText>Describes the Icon style to be applied to these records in search results</inlineHelpText>
        <label>Icon Style</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Community Tag</label>
    <nameField>
        <label>Community Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Theme__c.object
<CustomObject>
    <description>Will be used to roll up Tags to a Theme.  Depending on attributes of the Theme, related Tags may be used in the Community Registration process or available to associate to Resources.</description>
    <fields>
        <fullName>Icon_Style__c</fullName>
        <description>Describes the Icon style to be applied to these records in search results</description>
        <inlineHelpText>Describes the Icon style to be applied to these records in search results</inlineHelpText>
        <label>Icon Style</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Community Theme</label>
    <nameField>
        <label>Community Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Theme__c.object
    <fields>
        <fullName>Enable_in_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If TRUE, this theme will be presented to a Community user when registering for access to the community.</description>
        <label>Enable in Wizard</label>
        <type>Checkbox</type>
    </fields>

classes/CommunityDiscoverController.cls
public with sharing class CommunityDiscoverController extends CommunityGroupsBase {

	public List<CommunityThemeCategory> Themes { get; set; }
	public Community_Tag__c CurrentTag { get; set; }
	public List<String> EventsFieldsSet { get; set; }
	public List<String> GroupsFieldsSet { get; set; }
	public List<String> NewsFieldsSet { get; set; }
	public List<String> ResourcesFieldsSet { get; set; }

	public Boolean IsEventsRendered { get; set; }
	public Boolean IsGroupsRendered { get; set; }
	public Boolean IsNewsRendered { get; set; }
	public Boolean IsResourcesRendered { get; set; }

	public CommunityDiscoverController() {
		
		String tagId = ApexPages.currentPage().getParameters().get('t');
		if (String.isBlank(tagId)) {
			this.Themes = new List<CommunityThemeCategory>();

			List<Community_Tag__c> allTags = [
				SELECT Id, Community_Theme__c, Community_Theme__r.Name, Name, Icon_Style__c,
				(SELECT Id, Name FROM Events_Tag_Joins__r), 
				(SELECT Id, Name FROM Community_Tag_Group_Control__r), 
				(SELECT Id, Name FROM Community_Tag_News__r WHERE Community_News__r.Entry_Date__c >= TODAY AND Community_News__r.Expiration_Date__c <= TODAY), 
				(SELECT Id, Name FROM Resource_Tag_Joins__r) 
				FROM Community_Tag__c
			];
			Map<Id, List<Community_Tag__c>> themeTagsMap = new Map<Id, List<Community_Tag__c>>();
			for (Community_Tag__c tag : allTags) {
				Boolean eventsNotEmpty = !tag.Events_Tag_Joins__r.isEmpty();
				Boolean groupControlNotEmpty = !tag.Community_Tag_Group_Control__r.isEmpty();
				Boolean newsNotEmpty = !tag.Community_Tag_News__r.isEmpty();
				Boolean resourcesNotEmpty = !tag.Resource_Tag_Joins__r.isEmpty();
				if (eventsNotEmpty || groupControlNotEmpty || newsNotEmpty || resourcesNotEmpty) {

					List<Community_Tag__c> tags = themeTagsMap.containsKey(tag.Community_Theme__c) ? themeTagsMap.get(tag.Community_Theme__c) : new List<Community_Tag__c>();
					tags.add(tag);

					themeTagsMap.put(tag.Community_Theme__c, tags);
				}
			}
			List<Community_Theme__c> allThemes = [
				SELECT Id, Name
				FROM Community_Theme__c
				//WHERE Enable_in_Wizard__c = TRUE
				LIMIT 100
			];
			for (Community_Theme__c theme : allThemes) {
				if (themeTagsMap.containsKey(theme.Id)) {
					List<Community_Tag__c> tags = themeTagsMap.get(theme.Id);
					if (tags.size() > 0 ) {
						this.Themes.add(new CommunityThemeCategory(theme, tags));

					}
				}
			}

		} else {
			this.IsEventsRendered = false;
			this.IsGroupsRendered = false;
			this.IsNewsRendered = false;
			this.IsResourcesRendered = false;

			this.EventsFieldsSet = new List<String> { 'Name__c', 'Teaser__c', 'Start__c' }; //getFieldSet('EditEvent', Community_Events__c.sObjectType);
			this.GroupsFieldsSet = new List<String> { 'Name', 'Description__c', 'Image_Path__c' }; //getFieldSet('CreateGroup', Community_Group_Control__c.sObjectType);
			this.NewsFieldsSet = new List<String> { 'Title__c', 'Teaser__c', 'Entry_Date__c', 'Image_Path__c' }; //getFieldSet('ViewNews', Community_News__c.sObjectType);
			this.ResourcesFieldsSet = new List<String> { 'Name' }; //getFieldSet('CreateGroup', Community_Resource__c.sObjectType);

			if (this.EventsFieldsSet.isEmpty()) {
				this.EventsFieldsSet.add('Name');
			}
			if (this.GroupsFieldsSet.isEmpty()) {
				this.GroupsFieldsSet.add('Name');
			}
			if (this.NewsFieldsSet.isEmpty()) {
				this.NewsFieldsSet.add('Name');
			}
			if (this.ResourcesFieldsSet.isEmpty()) {
				this.ResourcesFieldsSet.add('Name');
			}

			String query = 'SELECT Id, Community_Theme__c, Community_Theme__r.Name, Name, ';
			query += String.format('(SELECT Id, {0} FROM Events_Tag_Joins__r), ', new List<String> { formatFieldSet(this.EventsFieldsSet, 'Community_Event__r')});
			query += String.format('(SELECT Id, {0} FROM Community_Tag_Group_Control__r), ', new List<String> { formatFieldSet(this.GroupsFieldsSet, 'Group_Control__r') });
			query += String.format('(SELECT Id, {0} FROM Community_Tag_News__r WHERE Community_News__r.Entry_Date__c >= TODAY AND Community_News__r.Expiration_Date__c >= TODAY), ', new List<String> { formatFieldSet(this.NewsFieldsSet, 'Community_News__r') });
			query += String.format('(SELECT Id, {0} FROM Resource_Tag_Joins__r) ', new List<String> { formatFieldSet(this.ResourcesFieldsSet, 'Resource__r') });
			query += 'FROM Community_Tag__c WHERE Id =: tagId ';
			system.debug(query);
			List<Community_Tag__c> allTags = Database.query(query);

			if (!allTags.isEmpty()) {
				this.CurrentTag = allTags.get(0);
				if (this.CurrentTag != NULL) {
					this.IsEventsRendered = !this.CurrentTag.Events_Tag_Joins__r.isEmpty();
					this.IsGroupsRendered = !this.CurrentTag.Community_Tag_Group_Control__r.isEmpty();
					this.IsNewsRendered = !this.CurrentTag.Community_Tag_News__r.isEmpty();
					this.IsResourcesRendered = !this.CurrentTag.Resource_Tag_Joins__r.isEmpty();
				}
			}
		}
	}

	public static List<List<Community_Tag__c>> chunkList(List<Community_Tag__c> oldArray, Integer chunkSize) {
		List<List<Community_Tag__c>> newArray = new List<List<Community_Tag__c>>();
		Integer arraySize = oldArray.size();

		for (Integer i=0; i < arraySize; i += chunkSize) {
			List<Community_Tag__c> innerArray = new List<Community_Tag__c>();
			for (Integer j = 0; j < chunkSize; j++) {
				Integer sliceValue = i+j;
				if (arraySize > sliceValue) {
					innerArray.add(oldArray[i+j]);
				}
			}

			newArray.add(innerArray);
		}
		system.debug(newArray);
        return newArray;
	}

	private static String formatFieldSet(List<String> fieldSet, String relationshipName) {
		String result = '';
		List<String> fieldSetCopy = new List<String>();
		for (String field : fieldSet) {
			field = relationshipName + '.' + field;
			fieldSetCopy.add(field);
		}
		return String.join(fieldSetCopy, ', ');
	}

	public class CommunityThemeCategory {
		public Community_Theme__c Theme { get; set; }
		public List<List<Community_Tag__c>> Tags { get; set; }

		public CommunityThemeCategory(Community_Theme__c t, List<Community_Tag__c> themeTags) {
			this.Theme = t;
			this.Tags = CommunityDiscoverController.chunkList(themeTags, 4);
		}
	}


	@RemoteAction
	public static DiscoverResultClass getGroups(Integer limitSize, Integer startFrom, String targetId) {
		String currentCommunityId = CommunityGroupsBase.getCurrentCommunityId();

		List<CollaborationGroupMember> collaborationGroupMemberList = [
			SELECT MemberId, Id, CollaborationRole,
				CollaborationGroupId,
				CollaborationGroup.Id, CollaborationGroup.Name, CollaborationGroup.Description,
				CollaborationGroup.InformationTitle, CollaborationGroup.InformationBody,
				CollaborationGroup.SmallPhotoUrl, CollaborationGroup.FullPhotoUrl, CollaborationGroup.MemberCount,
				CollaborationGroup.LastFeedModifiedDate,
				CollaborationGroup.OwnerId, CollaborationGroup.NetworkId, CollaborationGroup.IsArchived,
				CollaborationGroup.CollaborationType, CollaborationGroup.CanHaveGuests,
				CollaborationGroup.Owner.Name, CollaborationGroup.Owner.FirstName,
				CollaborationGroup.Owner.LastName, CollaborationGroup.Owner.SmallPhotoUrl
			FROM CollaborationGroupMember
			WHERE CollaborationGroup.NetworkId =: currentCommunityId
			AND MemberId =: UserInfo.getUserId()
			ORDER BY CollaborationGroup.Name
		];
		Map<Id, CollaborationGroupMember> CollaborationGroupMemberMap = new Map<Id, CollaborationGroupMember>();
		for (CollaborationGroupMember item : collaborationGroupMemberList) {
			CollaborationGroupMemberMap.put(item.CollaborationGroup.Id, item);
		}

		List<ChatterGroupDetail> result = new List<ChatterGroupDetail>();
		List<Community_Group_Control__c> allGroups = [
			SELECT Id, Name, Description__c, Image_Path__c,
			Chatter_Group_ID__c, Type__c
			FROM Community_Group_Control__c 
			WHERE Id IN (SELECT Group_Control__c FROM Community_Group_Control_Tag__c WHERE Community_Tag__c = :targetId AND Group_Control__c != NULL)
			AND Chatter_Group_ID__c != NULL
			LIMIT :limitSize 
			OFFSET :startFrom
		];
		Set<String> chatterGroupsIds = new Set<String>();
		for (Community_Group_Control__c item : allGroups) {
			chatterGroupsIds.add(item.Chatter_Group_ID__c);
		}
		//ALL MEMBERS
		List<CollaborationGroupMember> collaborationGroupMembersList = [
			SELECT MemberId, Id, CollaborationGroupId
			FROM CollaborationGroupMember
			WHERE CollaborationGroup.NetworkId =: currentCommunityId
			AND CollaborationGroupId IN :chatterGroupsIds
			ORDER BY CollaborationGroup.Name
		];
		Map<Id, Integer> groupMembersCountMap = new Map<Id, Integer>();
		for (CollaborationGroupMember item : collaborationGroupMembersList) {
			Integer cnt = groupMembersCountMap.containsKey(item.CollaborationGroupId) ? groupMembersCountMap.get(item.CollaborationGroupId) : 0;
			cnt += 1;
			groupMembersCountMap.put(item.CollaborationGroupId, cnt);
		}
		for (Community_Group_Control__c item : allGroups) {
			ChatterGroupDetail groupDetail = new ChatterGroupDetail(item);
			if (CollaborationGroupMemberMap.get(item.Id) == NULL) {
				groupDetail.CurrentMemberRole = 'NotAMember';
			}
			else {
				groupDetail.CurrentMemberRole = CollaborationGroupMemberMap.get(item.Id).CollaborationRole;
			}
			groupDetail.GroupMembersCount = groupMembersCountMap.containsKey(item.Chatter_Group_ID__c) ? groupMembersCountMap.get(item.Chatter_Group_ID__c) : 0;
			result.add(groupDetail);
		}
		DiscoverResultClass outputResult = new DiscoverResultClass(allGroups.size(), result);
		return outputResult;
	}
	@RemoteAction
	public static DiscoverResultClass getEvents(Integer limitSize, Integer startFrom, String targetId) {
		String currentCommunityId = CommunityGroupsBase.getCurrentCommunityId();
		
		List<Community_Events__c> pageRecords = [
			SELECT Id, Name__c, Teaser__c, Start__c
			FROM Community_Events__c 
			WHERE Id IN (SELECT Community_Event__c FROM Community_Event_Tag__c WHERE Community_Tag__c = :targetId)
			LIMIT :limitSize 
			OFFSET :startFrom
		];

		DiscoverResultClass outputResult = new DiscoverResultClass();
		outputResult.TotalRecords = pageRecords.size();
		outputResult.Events = pageRecords;
		return outputResult;
	}
	@RemoteAction
	public static DiscoverResultClass getNews(Integer limitSize, Integer startFrom, String targetId) {
		String currentCommunityId = CommunityGroupsBase.getCurrentCommunityId();

		List<Community_News__c> pageRecords = [
			SELECT Id, Image_Path__c, Teaser__c, Name, Title__c, Entry_Date__c
			FROM Community_News__c 
			WHERE Id IN (SELECT Community_News__c FROM Community_News_Tag__c WHERE Community_Tag__c = :targetId)
			LIMIT :limitSize 
			OFFSET :startFrom
		];

		DiscoverResultClass outputResult = new DiscoverResultClass();
		outputResult.TotalRecords = pageRecords.size();
		outputResult.News = pageRecords;
		return outputResult;
	}
}