src/objects/Community_Event_Tag__c.object
<CustomObject>
    <description>This object allows Tags and a Group to be associated to an Event record.</description>
    <fields>
        <fullName>Community_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated with this Event record.</description>
        <label>Community Event</label>
        <referenceTo>Community_Events__c</referenceTo>
        <relationshipLabel>Group &amp; Tags</relationshipLabel>
        <relationshipName>Events_Tag_Joins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Group_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows a Community Group to be associated with a Community Event.  Not mandatory.  Only used when joining a Community Event to a Chatter Group.</description>
        <label>Community Group Control</label>
        <referenceTo>Community_Group_Control__c</referenceTo>
        <relationshipLabel>Group Events</relationshipLabel>
        <relationshipName>Community_Event_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Event Tag</label>
    <nameField>
        <displayFormat>CET-{yy}{mm}{0}</displayFormat>
        <label>Community Event Tag</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Event Tag</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Events__c.object
<CustomObject>
    <description>Used to store Events in the Community.  Events may or may not be associated with a Group.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Provide a description of the Community Event details and RSVP instructions (if any)</description>
        <label>Description</label>
        <length>10000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>Start Date/Time of the Community Event Record</description>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Community Event</label>
    <nameField>
        <displayFormat>EVENT.{yy}{mm}{0}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Group_Control__c.object
<CustomObject>
    <description>Represents the metadata associated with a Chatter Group that is created in the Community.  Is used to serve up the Group Manager feed separately from the Chatter Group Feed.</description>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This defines the 18-digit SFID of the related Chatter Group for the Group Control record.</description>
        <label>Chatter Group ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Defines a description for the Group Control which will also be related to the Chatter Group, if needed.</description>
        <inlineHelpText>Write a brief description of your group.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Represents the Type of Group that will be created in the system.</description>
        <inlineHelpText>If your group will be public, any user may join.  If your group will be private, members must be added by a group manager.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Group Control</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Group Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Group_Control__c.object
    <fields>
        <fullName>Image_Path__c</fullName>
        <label>Image Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Community_News__c.object
<CustomObject>
    <description>This object stores News stories (links or text content) that are published to the Community.</description>
    <fields>
        <fullName>Image_Path__c</fullName>
        <description>Indicates the path where the image is stored and pulled from to display in the Community Portal.</description>
        <inlineHelpText>Indicates the path where the image is stored and pulled from to display in the Community Portal.</inlineHelpText>
        <label>Image Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates the type of news that is being added.  Internal represents a news article pasted into Salesforce and an External would be a link to an article posted somewhere on the internet.</description>
        <inlineHelpText>Indicates the type of news that is being added.  Internal represents a news article pasted into Salesforce and an External would be a link to an article posted somewhere on the internet.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community News</label>
    <nameField>
        <displayFormat>News.{yy}{mm}{0}</displayFormat>
        <label>News</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Resource__c.object
<CustomObject>
    <description>This object is used to store links to external systems and resource documents.  Resources will be organized by Themes and Tags where Theme.Type = Resource</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Represents a description of the Resource that is presented in the Community.</description>
        <inlineHelpText>Represents a description of the Resource that is presented in the Community.</inlineHelpText>
        <label>Description</label>
        <length>15000</length>
        <type>Html</type>
    </fields>
    <label>Community Resource</label>
    <nameField>
        <label>Resource Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Role__c</fullName>
        <description>This field describes the primary role or user experience in the Community.  The values of this field should match those of Community_Profile__c.RecordType.Name</description>
        <label>Primary Role</label>
        <picklist>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty/Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alumni</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CommunityGroupsBase.cls
public with sharing virtual class CommunityGroupsBase {
	public String SitePrefix {
		get {
			if (this.SitePrefix == NULL) {
				this.SitePrefix = Site.getPathPrefix();
			}
			return this.SitePrefix;
		}
		private set;
	}
	public CommunityGroupsBase() {

	}


	public static String getCurrentCommunityId() {
		/*ConnectApi.CommunityPage cp = ConnectApi.Communities.getCommunities();
		String currentPathPrefix = Site.getPathPrefix().replaceAll('/', '');
		for (ConnectApi.Community c : cp.communities) {
			if (currentPathPrefix.equalsIgnoreCase(c.urlPathPrefix)) {
				return c.Id;
			}
		}*/
		return Network.getNetworkId();
	}
	public static String getMemberRole(ConnectApi.GroupMembershipType memberRole) {
		/*
			GroupOwner
			GroupManager
			NotAMember
			NotAMemberPrivateRequested
			StandardMember
		*/
		String result = NULL;
		if (memberRole == ConnectApi.GroupMembershipType.GroupOwner) {
			result = 'Owner';
		} else if (memberRole == ConnectApi.GroupMembershipType.GroupManager) {
			result = 'Manager';
		} else if (memberRole == ConnectApi.GroupMembershipType.StandardMember) {
			result = 'Member';
		} else {
			result = 'NotAMember';
		}
		return result;
	}

	public static String getMemberRole(String memberRole) {
		/*
			GroupOwner
			GroupManager
			NotAMember
			NotAMemberPrivateRequested
			StandardMember
		*/
		String result = NULL;
		if (memberRole == 'Admin') {
			result = 'Owner';
		} else if (memberRole == 'Manager') {
			result = 'Manager';
		} else if (memberRole == 'Standard') {
			result = 'Member';
		} else {
			result = 'NotAMember';
		}
		return result;
	}

	public static List<Community_Events__c> getUpcomingEventsForGroup(Id groupId) {
		/*
		Display any Community_Event__c records
		where there is a Community_Event_Tag__c record that is linked to this Chatter Group
		(see requirement 1.c.ii above) && Event Start Date >! TODAY()
		*/
		List<Community_Event_Tag__c> linkedTags = [
			SELECT Id, Community_Event__c, Community_Event__r.Id
			FROM  Community_Event_Tag__c
			WHERE Community_Group_Control__r.Chatter_Group_ID__c =: groupId
			AND Community_Event__c != NULL
			AND Community_Event__r.Start__c >= TODAY
		];
		Set<Community_Events__c> eventsSet = new Set<Community_Events__c>();
		for (Community_Event_Tag__c tag : linkedTags) {
			eventsSet.add(tag.Community_Event__r);
		}
		List<Community_Events__c> events = new List<Community_Events__c>(eventsSet);
		return events;
	}

	/*public List<String> getFieldSet(String fieldSetName, Schema.SObjectType objectName) {
		Map<String, Schema.SObjectType> GlobalDescribeMap = Schema.getGlobalDescribe();
		Schema.SObjectType SObjectTypeObj = GlobalDescribeMap.get(String.valueOf(objectName));
		Schema.DescribeSObjectResult DescribeSObjectResultObj = SObjectTypeObj.getDescribe();
		Schema.FieldSet fieldSetObj = DescribeSObjectResultObj.FieldSets.getMap().get(fieldSetName);

		List<String> result = new List<String>();
		if (fieldSetObj != NULL) {
			for (Schema.FieldSetMember field : fieldSetObj.getFields()) {
				result.add(field.getFieldPath());
			}
		}
		return result;
	}*/
	public List<String> getFieldSet(String fieldSetName, Schema.SObjectType objectType) {
		Schema.FieldSet fieldSetObj = NULL;
		if (objectType == Community_Group_Control__c.getSObjectType()) {
			fieldSetObj = SObjectType.Community_Group_Control__c.FieldSets.getMap().get(fieldSetName);
		} else if (objectType == Community_Resource__c.getSObjectType()) {
			fieldSetObj = SObjectType.Community_Resource__c.FieldSets.getMap().get(fieldSetName);
		} else  if (objectType == Community_News__c.getSObjectType()) {
			fieldSetObj = SObjectType.Community_News__c.FieldSets.getMap().get(fieldSetName);
		} else  if (objectType == Community_Events__c.getSObjectType()) {
			fieldSetObj = SObjectType.Community_Events__c.FieldSets.getMap().get(fieldSetName);
		}

		List<String> result = new List<String>();
		if (fieldSetObj != NULL) {
			for (Schema.FieldSetMember field : fieldSetObj.getFields()) {
				result.add(field.getFieldPath());
			}
		}
		return result;
	}

	public class ChatterGroupDetail {
		public Id GroupId { get; set; }
		public Id GroupControlId { get;set; }
		public String GroupName { get; set; }
		public String GroupDescription { get; set; }
		public String GroupPhotoUrl {
			get {
				if (String.isBlank(this.GroupPhotoUrl)) {
					this.GroupPhotoUrl = '/profilephoto/0F9/F';
				}
				this.GroupPhotoUrl = this.GroupPhotoUrl.replace(Site.getBaseUrl(), '');
				return this.GroupPhotoUrl;
			}
			set;
		}
		public String GroupVisibility { get; set; }
		public List<ChatterGroupMember> Members { get; set; }
		public List<Community_Events__c> UpcomingEvents { get; set; }
		public String CurrentMemberRole { get; set; }
		public Integer GroupMembersCount {
			get {
				if (this.GroupMembersCount == NULL) {
					if (this.Members != NULL) {
						this.GroupMembersCount = this.Members.size();
					}
				}
				return this.GroupMembersCount;
			}
			set;
		}
		public Datetime GroupLastActivityDate { get; set; }
		public String GroupLastActivityDateFormatted { get { 
				if (String.isBlank(this.GroupLastActivityDateFormatted) && this.GroupLastActivityDate != NULL) {
					this.GroupLastActivityDateFormatted = formatActivityDate();
				}
				return this.GroupLastActivityDateFormatted;
			}
			set;
		}
		private String formatActivityDate() {
			return String.format('{0} at {1}',
				new List<String> {
					this.GroupLastActivityDate.format('MMMMM d, yyyy'),
					this.GroupLastActivityDate.format('HH:mm a')
				}
			);
		}
		public ChatterGroupMember GroupOwner { get; set; }

		public ChatterGroupDetail(String communityId, ConnectApi.ChatterGroupDetail groupDetail) {
			this.GroupId = groupDetail.Id;
			this.GroupName = groupDetail.Name;
			this.GroupDescription = groupDetail.Description;
			this.GroupPhotoUrl = (groupDetail.Photo != NULL) ? groupDetail.Photo.LargePhotoUrl : NULL;
			this.GroupVisibility = (groupDetail.Visibility == ConnectApi.GroupVisibilityType.PublicAccess) ? 'Public' : 'Private';
			this.CurrentMemberRole = CommunityGroupsBase.getMemberRole(groupDetail.MyRole);
			this.Members = new List<ChatterGroupMember>();

			ConnectApi.GroupMemberPage groupMemberPage = ConnectApi.ChatterGroups.getMembers(communityId, groupDetail.Id);
			if (groupMemberPage != NULL) {
				for (ConnectApi.GroupMember member : groupMemberPage.Members) {
					this.Members.add(new ChatterGroupMember(member));
				}
			}
			this.UpcomingEvents = CommunityGroupsBase.getUpcomingEventsForGroup(groupDetail.Id);
		}
		public ChatterGroupDetail(ConnectApi.ChatterGroupDetail groupDetail) {
			this.GroupId = groupDetail.Id;
			this.GroupName = groupDetail.Name;
			this.GroupDescription = groupDetail.Description;
			this.GroupPhotoUrl = (groupDetail.Photo != NULL) ? groupDetail.Photo.LargePhotoUrl : NULL;
			this.GroupVisibility = (groupDetail.Visibility == ConnectApi.GroupVisibilityType.PublicAccess) ? 'Public' : 'Private';
			this.CurrentMemberRole = CommunityGroupsBase.getMemberRole(groupDetail.MyRole);
			this.Members = new List<ChatterGroupMember>();
			this.GroupMembersCount = groupDetail.MemberCount;
			this.GroupLastActivityDate = groupDetail.LastFeedElementPostDate;
			this.GroupLastActivityDateFormatted = formatActivityDate();
			this.GroupOwner = new ChatterGroupMember(groupDetail.Owner);
		}
		public ChatterGroupDetail(CollaborationGroup groupDetail) {
			this.GroupId = groupDetail.Id;
			this.GroupName = groupDetail.Name;
			this.GroupDescription = groupDetail.Description;
			this.GroupPhotoUrl = groupDetail.FullPhotoUrl;
			this.GroupVisibility = groupDetail.CollaborationType;
			this.Members = new List<ChatterGroupMember>();
			this.GroupMembersCount = groupDetail.MemberCount;
			this.GroupLastActivityDate = groupDetail.LastFeedModifiedDate;
			this.GroupLastActivityDateFormatted = formatActivityDate();
			this.GroupOwner = new ChatterGroupMember(groupDetail.Owner);
		}
		public ChatterGroupDetail(Community_Group_Control__c groupDetail) {
			this.GroupId = groupDetail.Id;
			if (groupDetail.Chatter_Group_ID__c != NULL) {
				//CollaborationGroup cg = [SELECT FullPhotoUrl FROM CollaborationGroup WHERE Id =:groupDetail.Chatter_Group_ID__c];
				this.GroupId = groupDetail.Chatter_Group_ID__c;
				//this.GroupPhotoUrl = cg.FullPhotoUrl;
			}
			this.GroupPhotoUrl = (groupDetail.Image_Path__c != NULL) ? groupDetail.Image_Path__c : '/studentcommunity/profilephoto/0F9/F';
			this.GroupControlId = groupDetail.Id;
			this.GroupName = groupDetail.Name;
			this.GroupDescription = groupDetail.Description__c;
			this.GroupVisibility = groupDetail.Type__c;
			this.Members = new List<ChatterGroupMember>();
		}
	}

	public class ChatterGroupMember {
		public Id MemberId { get; set; }
		public String MemberName { get; set; }
		public String MemberRole { get; set; }
		public String MemberContactRole { get; set; }
		public String MemberPhotoUrl {
			get {
				if (String.isBlank(this.MemberPhotoUrl)) {
					this.MemberPhotoUrl = '/profilephoto/005/T';
				}
				this.MemberPhotoUrl = this.MemberPhotoUrl.replace(Site.getBaseUrl(), '');
				return this.MemberPhotoUrl;
			}
			set;
		}
		public String SubscriptionId { get; set; }
		public Boolean MemberIsFollowing { get; set; }

		public ChatterGroupMember(ConnectApi.GroupMember member) {
			this.MemberId = member.User.Id;
			this.MemberName = String.format('{0}{1}',
				new List<String> {
					!String.isBlank(member.User.FirstName) ? member.User.FirstName + ' ' : '',
					!String.isBlank(member.User.LastName) ? member.User.LastName : ''
				}
			);
			this.MemberRole = CommunityGroupsBase.getMemberRole(member.Role);
			this.MemberPhotoUrl = (member.User.Photo != NULL) ? member.User.Photo.SmallPhotoUrl : NULL;
		}

		public ChatterGroupMember(ConnectApi.UserSummary member) {
			this.MemberId = member.Id;
			this.MemberName = String.format('{0}{1}',
				new List<String> {
					!String.isBlank(member.FirstName) ? member.FirstName + ' ' : '',
					!String.isBlank(member.LastName) ? member.LastName : ''
				}
			);
			//this.MemberRole = CommunityGroupsBase.getMemberRole(member.Role);
			this.MemberPhotoUrl = (member.Photo != NULL) ? member.Photo.SmallPhotoUrl : NULL;
		}

		public ChatterGroupMember(User member) {
			this.MemberId = member.Id;
			this.MemberName = String.format('{0}{1}',
				new List<String> {
					!String.isBlank(member.FirstName) ? member.FirstName + ' ' : '',
					!String.isBlank(member.LastName) ? member.LastName : ''
				}
			);
			//this.MemberRole = CommunityGroupsBase.getMemberRole(member.Role);
			this.MemberPhotoUrl = member.SmallPhotoUrl;
			//this.MemberContactRole = member.Contact != NULL ? member.Contact.Primary_Role__c : NULL;
		}
		public ChatterGroupMember(User member, Boolean isFollowing) {
			this.MemberId = member.Id;
			this.MemberName = String.format('{0}{1}',
				new List<String> {
					!String.isBlank(member.FirstName) ? member.FirstName + ' ' : '',
					!String.isBlank(member.LastName) ? member.LastName : ''
				}
			);
			//this.MemberRole = CommunityGroupsBase.getMemberRole(member.Role);
			this.MemberPhotoUrl = member.SmallPhotoUrl;
			this.MemberIsFollowing = isFollowing;
			this.MemberContactRole = member.Contact != NULL ? member.Contact.Primary_Role__c : NULL;
		}
		public ChatterGroupMember(User member, Boolean isFollowing, String SubscriptionId) {
			this.MemberId = member.Id;
			this.MemberName = String.format('{0}{1}',
				new List<String> {
					!String.isBlank(member.FirstName) ? member.FirstName + ' ' : '',
					!String.isBlank(member.LastName) ? member.LastName : ''
				}
			);
			//this.MemberRole = CommunityGroupsBase.getMemberRole(member.Role);
			this.MemberPhotoUrl = member.SmallPhotoUrl;
			this.MemberIsFollowing = isFollowing;
			this.MemberContactRole = member.Contact != NULL ? member.Contact.Primary_Role__c : NULL;
			this.SubscriptionId = SubscriptionId;
		}

		public ChatterGroupMember(CollaborationGroupMember member) {
			this.MemberId = member.MemberId;
			this.MemberName = String.format('{0}{1}',
				new List<String> {
					!String.isBlank(member.Member.FirstName) ? member.Member.FirstName + ' ' : '',
					!String.isBlank(member.Member.LastName) ? member.Member.LastName : ''
				}
			);
			this.MemberRole = member.CollaborationRole;
			this.MemberPhotoUrl =  member.Member.SmallPhotoUrl;
		}
	}
	public class DiscoverResultClass {
		public Integer TotalRecords { get; set; }
		public List<ChatterGroupDetail> Groups  { get; set; }
		public List<Community_News__c> News  { get; set; }
		public List<Community_Events__c> Events  { get; set; }
		public Boolean HasMore { get; set; }

		public DiscoverResultClass(Integer total, List<ChatterGroupDetail> groupsList) {
			this.TotalRecords = total;
			this.Groups = groupsList;
		}

		public DiscoverResultClass() {
		}
	}
}