src/objects/Community_Group_Control__c.object
<CustomObject>
    <description>Represents the metadata associated with a Chatter Group that is created in the Community.  Is used to serve up the Group Manager feed separately from the Chatter Group Feed.</description>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This defines the 18-digit SFID of the related Chatter Group for the Group Control record.</description>
        <label>Chatter Group ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Community Group Control</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Group Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Group_Membership__c.object
<CustomObject>
    <fields>
        <fullName>Group_Control__c</fullName>
        <description>Represents the Group the Group Membership record is related to.</description>
        <inlineHelpText>Represents the Group the Group Membership record is related to.</inlineHelpText>
        <label>Group Control</label>
        <referenceTo>Community_Group_Control__c</referenceTo>
        <relationshipLabel>Group Managers</relationshipLabel>
        <relationshipName>Community_Group_Managers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group_Membership_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the User that has access to the Group Control record in the Community.</description>
        <inlineHelpText>This is the User that has access to the Group Control record in the Community.</inlineHelpText>
        <label>Group Membership User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Group_Membershps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Group Manager</label>
    <nameField>
        <displayFormat>CGM.{yy}{mm}{0}</displayFormat>
        <label>Group Manager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Group Managers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CommunityFeedNavigationController.cls
public with sharing class CommunityFeedNavigationController {
/*
	// -- common variables --
	public User currentUser { get; set; }
	public String SitePrefix {
		get {
			if (this.SitePrefix == NULL) {
				this.SitePrefix = Site.getPathPrefix();
			}
			return this.SitePrefix;
		}
		private set;
	}
	public String currentPanel { get; set; }
	public String currentElement { get; set; }
	public Boolean isAllowMessage { get; set; }
	private final String CurrentCommunityId = CommunityGroupsBase.getCurrentCommunityId();

	//CONSTRUCTOR
	public CommunityFeedNavigationController() {

		List<User> userList = new List<User>();

		userList = getListUsersFromId(UserInfo.getUserId());
		if (!userList.isEmpty()) {
			this.currentUser = userList[0];
		}

		isAllowMessage = true;

		try {
//			ConnectApi.?Chatter?ConversationPage conversationPage =
				ConnectApi.ChatterMessages.getConversations(CurrentCommunityId);
		}
		catch (exception e) {
			isAllowMessage = false;
		}

		return;
	}


	//PUBLIC METHODS




	//PRIVATE METHODS


	//GET CurrentUser
	private List<User> getListUsersFromId(String userId) {

		List<User> result = new List<User>();

		if (!String.isBlank(userId)) {
			result = [
				SELECT Id, FirstName, LastName
				FROM User
				WHERE Id =: userId
				LIMIT 1
			];
		}

		return result;
	}
*/

	public Integer MessageUnreadCount { get; set; }
	public Boolean showMessages {
		get {
			Boolean result = true;
			try {
				ConnectApi.ChatterConversationPage cp = ConnectApi.ChatterMessages.getConversations(Network.getNetworkId());
				ConnectApi.UnreadConversationCount unreadCount = ConnectApi.ChatterMessages.getUnreadCount(CommunityGroupsBase.getCurrentCommunityId());
				MessageUnreadCount  = unreadCount.UnreadCount;
			}
			catch (exception e) {
				result = false;
			}
			return result;
		}
	}

	public Boolean showGroupManager {
		get {
			if(ApexPages.currentPage().getParameters().containsKey('g'))
			{
				String groupId = ApexPages.currentPage().getParameters().get('g');
				List<Community_Group_Membership__c> cgmList = [SELECT Id FROM Community_Group_Membership__c WHERE Group_Membership_User__c = :UserInfo.getUserId() AND Group_Control__r.Chatter_Group_ID__c = :groupId];
				return cgmList.size() > 0;
			} else {
				return false;
			}
		}
	}
}