src/objects/Community_Event_Tag__c.object
<CustomObject>
    <description>This object allows Tags and a Group to be associated to an Event record.</description>
    <fields>
        <fullName>Community_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated with this Event record.</description>
        <label>Community Event</label>
        <referenceTo>Community_Events__c</referenceTo>
        <relationshipLabel>Group &amp; Tags</relationshipLabel>
        <relationshipName>Events_Tag_Joins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated with this Event record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>Event Items Tagged</relationshipLabel>
        <relationshipName>Community_EventItems_Tagged</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Event Tag</label>
    <nameField>
        <displayFormat>CET-{yy}{mm}{0}</displayFormat>
        <label>Community Event Tag</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Event Tag</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Events__c.object
<CustomObject>
    <description>Used to store Events in the Community.  Events may or may not be associated with a Group.</description>
    <label>Community Event</label>
    <nameField>
        <displayFormat>EVENT.{yy}{mm}{0}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Group_Control__c.object
<CustomObject>
    <description>Represents the metadata associated with a Chatter Group that is created in the Community.  Is used to serve up the Group Manager feed separately from the Chatter Group Feed.</description>
    <label>Community Group Control</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Group Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Group_Control_Tag__c.object
<CustomObject>
    <description>This object allows tags to be associated with a Group Control record.</description>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <description>This defines the Tag that is being associated to the Group Control</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>Group Items Tagged</relationshipLabel>
        <relationshipName>Community_GroupItems_Tagged</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group_Control__c</fullName>
        <description>This field defines the Group that tags will be associated with</description>
        <label>Group Control</label>
        <referenceTo>Community_Group_Control__c</referenceTo>
        <relationshipLabel>Group Tags</relationshipLabel>
        <relationshipName>Community_Group_Tags</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community Group Control Tag</label>
    <nameField>
        <displayFormat>CGCT-{yy}{mm}{0}</displayFormat>
        <label>Community Group Control Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Group Control Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_News__c.object
<CustomObject>
    <description>This object stores News stories (links or text content) that are published to the Community.</description>
    <label>Community News</label>
    <nameField>
        <displayFormat>News.{yy}{mm}{0}</displayFormat>
        <label>News</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_News_Tag__c.object
<CustomObject>
    <description>This object allows Tags to be associated to a Community News record.</description>
    <fields>
        <fullName>Community_News__c</fullName>
        <description>Allows tags to be associated with this Community News record.</description>
        <label>Community News</label>
        <referenceTo>Community_News__c</referenceTo>
        <relationshipLabel>News Tags</relationshipLabel>
        <relationshipName>Community_News_Tag</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <description>Defines the tag that is being associated with the News record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>News Items Tagged</relationshipLabel>
        <relationshipName>Community_NewItems_Tagged</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community News Tag</label>
    <nameField>
        <displayFormat>CNT-{yy}{mm}{0}</displayFormat>
        <label>Community News Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_Resource__c.object
<CustomObject>
    <description>This object is used to store links to external systems and resource documents.  Resources will be organized by Themes and Tags where Theme.Type = Resource</description>
    <fields>
        <fullName>Primary_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Define the primary tag used to categorize and organize this resource in the Resource Library list view.  Additional tags may also be associated separately.</description>
        <label>Primary Tag</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Community_Tag__c.Community_Theme__r.Theme_Type__c</field>
                <operation>equals</operation>
                <value>Resource</value>
            </filterItems>
            <infoMessage>You can only select Tags where the Theme Type = Resource.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>Resources Tagged w Primary</relationshipLabel>
        <relationshipName>Resource_Tagged_w_Primary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of a resource will determine whether it is visible in the Community.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Resource</label>
    <nameField>
        <label>Resource Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Resource_Tag__c.object
<CustomObject>
    <description>This object allows tags to be associated with a Resource record.</description>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <description>This defines the Tag that is being associated to the Resource</description>
        <label>Community Tag</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Community_Tag__c.Community_Theme__r.Theme_Type__c</field>
                <operation>equals</operation>
                <value>Interest, System</value>
            </filterItems>
            <infoMessage>You can only select Tags where Theme Type = Interest.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>Resource Items Tagged</relationshipLabel>
        <relationshipName>Community_ResourceItems_Tagged</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <description>This defines the Resource that is being associated with the Tag.</description>
        <label>Resource</label>
        <referenceTo>Community_Resource__c</referenceTo>
        <relationshipLabel>Resource Tags</relationshipLabel>
        <relationshipName>Community_Resource_Tags</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community Resource Tag</label>
    <nameField>
        <displayFormat>CRT-{yy}{mm}{0}</displayFormat>
        <label>Community Resource Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Resource Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_Tag__c.object
<CustomObject>
    <description>Define a library of Tags that will help categorize interests for the Community.  Tags can be associated to Community News, Events, Groups, and Contacts via separate junction objects.  This will allow the starter pack to recommend items to a Community user.</description>
    <fields>
        <fullName>Community_Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the Theme of the Community Tag.</description>
        <inlineHelpText>Represents the Theme of the Community Tag.</inlineHelpText>
        <label>Community Theme</label>
        <referenceTo>Community_Theme__c</referenceTo>
        <relationshipLabel>Community Tags</relationshipLabel>
        <relationshipName>Community_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Icon_Style__c</fullName>
        <description>Describes the Icon style to be applied to these records in search results</description>
        <inlineHelpText>Describes the Icon style to be applied to these records in search results</inlineHelpText>
        <label>Icon Style</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theme_Type__c</fullName>
        <description>Represents the Theme Type of the Theme related to the Tag.</description>
        <formula>TEXT(Community_Theme__r.Theme_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Represents the Theme Type of the Theme related to the Tag.</inlineHelpText>
        <label>Theme Type</label>
        <type>Text</type>
    </fields>
    <label>Community Tag</label>
    <nameField>
        <label>Community Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Theme__c.object
<CustomObject>
    <description>Will be used to roll up Tags to a Theme.  Depending on attributes of the Theme, related Tags may be used in the Community Registration process or available to associate to Resources.</description>
    <fields>
        <fullName>Icon_Color__c</fullName>
        <description>Choose from any of Font Awesome&apos;s Icon coloring classes</description>
        <inlineHelpText>Choose from any of Font Awesome&apos;s Icon coloring classes</inlineHelpText>
        <label>Icon Color</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon_Style__c</fullName>
        <description>Describes the Icon style to be applied to these records in search results</description>
        <inlineHelpText>Describes the Icon style to be applied to these records in search results</inlineHelpText>
        <label>Icon Style</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theme_Type__c</fullName>
        <description>determines if the theme will be available for resources, interests or system</description>
        <label>Theme Type</label>
        <picklist>
            <picklistValues>
                <fullName>Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Theme</label>
    <nameField>
        <label>Community Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommunityTopCategoriesController.cls
/* 
 * Unity - Communities
 * 
 * Community is critical to the student experience--but building community is 
 * just plain hard. Built on Communities and designed specifically for higher ed, 
 * Unity is a powerful networking tool to help you generate engagement and 
 * connect your campus.
 * 
 * Copyright (C) 2015 Motivis Learning Systems Inc.
 * 
 * This program is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * 
 * To contact Motivis Learning Systems Inc.
 * 25 Pelham Road
 * Salem, NH 03790
 * unity@motivislearning.com
 */

public with sharing class CommunityTopCategoriesController {
	// COMMON VARIABLES
	public Boolean resourceOnly { get; set; }
	public static Integer countCol { get; set; }
	public Boolean compRendered { get; set; }

	//CONTROLLER
	public CommunityTopCategoriesController() {
	}

	public void setColumns(){
		compRendered = true;
	}


	//GET DATA LIST
	public List<themeTagWapper> getWrappedThemes() {
		countCol = countCol != null ? countCol : 3;
		compRendered = compRendered != null ? compRendered : false;
		List<themeTagWapper> resultList = new List<themeTagWapper>();
		if (!SObjectType.Community_Tag__c.isAccessible()) CommunityAccess.ThrowAccessException(SObjectType.Community_Tag__c);
		List<Community_Tag__c> allTags = [
			SELECT Id, Community_Theme__c, Community_Theme__r.Icon_Color__c, Community_Theme__r.Name, Name, Icon_Style__c,
			(SELECT Id, Name FROM Community_EventItems_Tagged__r WHERE Community_Event__r.Public__c = true),
			(SELECT Id, Name FROM Community_GroupItems_Tagged__r WHERE Group_Control__r.Discoverable__c = true),
			(SELECT Id, Name FROM Community_NewItems_Tagged__r WHERE Community_News__r.Entry_Date__c <= TODAY AND Community_News__r.Alert__c = false),
			(SELECT Id, Resource__c FROM Community_ResourceItems_Tagged__r WHERE Resource__r.Status__c = 'active'),
			(SELECT Id, Name FROM Resource_Tagged_w_Primary__r WHERE Status__c = 'active')
			FROM Community_Tag__c ORDER BY Name ASC
				];
		Map<Id,List<Community_Tag__c>> themeTagsMap = new Map<Id,List<Community_Tag__c>>();
		for (Community_Tag__c tag : allTags) {
			if (resourceOnly != true || tag.Resource_Tagged_w_Primary__r.size() > 0) {
				if(!themeTagsMap.containsKey(tag.Community_Theme__c)) {
					themeTagsMap.put(tag.Community_Theme__c, new List<Community_Tag__c>());
				}
				themeTagsMap.get(tag.Community_Theme__c).add(tag);
			}
		}
		 if (!SObjectType.Community_Theme__c.isAccessible()) CommunityAccess.ThrowAccessException(SObjectType.Community_Theme__c);
		String queryString = 'SELECT Id, Name, Icon_Color__c FROM Community_Theme__c';
		queryString += ' WHERE Theme_Type__c = \'' + (resourceOnly == true ? 'Resource' : 'Interest') + '\'';
		Set<Id> filteredThemes;
		if (resourceOnly == true && themeTagsMap.size() > 0) {
			filteredThemes = themeTagsMap.keySet();
			queryString += ' AND Id IN :filteredThemes';
		}
		queryString += ' ORDER BY Name';
		if (resourceOnly != true || themeTagsMap.size() > 0) {
			for(Community_Theme__c theme : Database.query(queryString)) {
				resultList.add(new themeTagWapper(theme, themeTagsMap.get(theme.Id), resourceOnly == true));
			}
		}

		return resultList;
	}

	//WRAPPERS
	public class themeTagWapper {
		public String themeName { get; set; }
		public String themeId { get; set; }
		public String themeIconColor { get; set; }
		public List<List<themeTagItem>> tagColumns { get; set; }

		public themeTagWapper(Community_Theme__c t, List<Community_Tag__c> tags, Boolean inRO) {
			themeName = t.Name;
			themeId = t.Id;
			themeIconColor = t.Icon_Color__c;
			tagColumns = new List<List<themeTagItem>>();
			if (tags != NULL && tags.size() > 0) {
                Integer breakpoint = tags.isEmpty() ? 0 : (tags.size() / countCol);
                Integer remainder = Math.mod(tags.size(), countCol);
				for(Integer colCount = 0; colCount < countCol; colCount++) {
					tagColumns.add(new List<themeTagItem>());
				}
				Integer tagCount = 0;
				Integer currentColumn = 0;
				for (Community_Tag__c tag : tags) {
					Set<Id> calculateResources = new Set<Id>();
					for (Community_Resource_Tag__c crt : tag.Community_ResourceItems_Tagged__r) {
						calculateResources.add(crt.Resource__c);
					}
					for (Community_Resource__c cr : tag.Resource_Tagged_w_Primary__r) {
						calculateResources.add(cr.Id);
					}
					Integer accumulateTags = inRO ? calculateResources.size(): (tag.Community_EventItems_Tagged__r.size() + tag.Community_GroupItems_Tagged__r.size() + tag.Community_NewItems_Tagged__r.size());
					tagColumns[currentColumn].add(new themeTagItem(tag, accumulateTags, inRO));
                    if (tagCount == breakpoint || ((breakpoint - tagCount == 1) && remainder == 0)) {
						currentColumn++;
						tagCount = 0;
                        remainder = (remainder == 0 ? 0 : (remainder - 1));
					}
					else {
						tagCount++;
					}
				}
                List<List<themeTagItem>> tempTagColumns = new List<List<themeTagItem>>();
                for (Integer colCount = 0; colCount <= breakpoint; colCount++) {
                    tempTagColumns.add(new List<themeTagItem>());
                }

                for (Integer i = 0; i <= breakpoint; i++) {
                    for (Integer j = 0; j < countCol; j++) {
                        if (tagColumns.get(j) != null && tagColumns.get(j).size() >= (i + 1) && tagColumns.get(j).get(i) != null) {
                            tempTagColumns.get(i).add(tagColumns.get(j).get(i));
                        }
                        else {
                            break;
                        }
                    }
                }
                tagColumns = tempTagColumns;
			}
		}
	}

	public class themeTagItem {
		public String Parameter { get; set; }
		public String name { get; set; }
		public String iconStyle { get; set; }
		public String total { get; set; }

		public themeTagItem(Community_Tag__c inTag, Integer inTotal, Boolean inRO2) {
			Parameter = (inRO2 ? 'tr=' : 't=') + inTag.Id;
			name = inTag.Name;
			iconStyle = inTag.Icon_Style__c;
			total = String.valueOf(inTotal);
		}
	}
}