src/objects/Community_News__c.object
<CustomObject>
    <description>This object stores News stories (links or text content) that are published to the Community.</description>
    <fields>
        <fullName>Allow_Comments__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When selected, Community Users will be allowed to post Comments on a news article as long as the Comment Expiration has not passed.</description>
        <inlineHelpText>When selected, Community Users will be allowed to post Comments on a news article as long as the Comment Expiration has not passed.</inlineHelpText>
        <label>Allow Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comment_Expiration_Date__c</fullName>
        <description>Represents the Date/Time when the News Article prevents new comments from being added to the News Article.  The Time is based on the Organizations Time Zone listed in Salesforce.</description>
        <inlineHelpText>Represents the Date/Time when the News Article prevents new comments from being added to the News Article.  The Time is based on the Organizations Time Zone listed in Salesforce.</inlineHelpText>
        <label>Comment Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>Represents the full text description of the news article that will be displayed in the Community Portal.</description>
        <inlineHelpText>Represents the full text description of the news article that will be displayed in the Community Portal.</inlineHelpText>
        <label>Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <description>Represents the Date/Time when the News Article will be posted in the Community Portal.  This will be based on the Organizations Time Zone in Salesforce.</description>
        <inlineHelpText>Represents the Date/Time when the News Article will be posted in the Community Portal.  This will be based on the Organizations Time Zone in Salesforce.</inlineHelpText>
        <label>Entry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Represents the Date/Time when the News Article will be removed from the Community Portal.  The time will be based on the Organizations Time Zone in Salesforce.</description>
        <inlineHelpText>Represents the Date/Time when the News Article will be removed from the Community Portal.  The time will be based on the Organizations Time Zone in Salesforce.</inlineHelpText>
        <label>Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Image_Path__c</fullName>
        <description>Indicates the path where the image is stored and pulled from to display in the Community Portal.</description>
        <inlineHelpText>Indicates the path where the image is stored and pulled from to display in the Community Portal.</inlineHelpText>
        <label>Image Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make_Entry_Sticky__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When selected, the News Article will always appear at the top of the News Article Listed.  If multiple active Sticky, articles will be listed in Descending Order by Entry Date field.</description>
        <inlineHelpText>When selected, the News Article will always appear at the top of the News Article Listed.  If multiple active Sticky, articles will be listed in Descending Order by Entry Date field.</inlineHelpText>
        <label>Make Entry Sticky</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Teaser__c</fullName>
        <description>Represents a short description of the News article that will be posted in the Community Portal.</description>
        <inlineHelpText>Represents a short description of the News article that will be posted in the Community Portal.</inlineHelpText>
        <label>Teaser</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Represents the title of the news that will be displayed in the Community Portal.</description>
        <inlineHelpText>Represents the title of the news that will be displayed in the Community Portal.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates the type of news that is being added.  Internal represents a news article pasted into Salesforce and an External would be a link to an article posted somewhere on the internet.</description>
        <inlineHelpText>Indicates the type of news that is being added.  Internal represents a news article pasted into Salesforce and an External would be a link to an article posted somewhere on the internet.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>Allows a hyperlink to be provided for an External news story.</description>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Community News</label>
    <nameField>
        <displayFormat>News.{yy}{mm}{0}</displayFormat>
        <label>News</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_News__c.object
    <fields>
        <fullName>Breaking_News__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies that news article appears in the News Ticker.</description>
        <inlineHelpText>Identifies that news article appears in the News Ticker.</inlineHelpText>
        <label>Breaking News</label>
        <type>Checkbox</type>
    </fields>

src/objects/Community_News_Tag__c.object
<CustomObject>
    <description>This object allows Tags to be associated to a Community News record.</description>
    <fields>
        <fullName>Allow_Comments__c</fullName>
        <description>Indicates if the related News article allows user&apos;s to comment on it.</description>
        <formula>Community_News__r.Allow_Comments__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The News article allows user&apos;s to comment on it.</inlineHelpText>
        <label>Allow Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comment_Expiration_Date__c</fullName>
        <description>Represents the date when comments are no longer accepted for the related News article.</description>
        <formula>Community_News__r.Comment_Expiration_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Date when comments are no longer accepted for this News article.</inlineHelpText>
        <label>Comment Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Community_News__c</fullName>
        <description>Allows tags to be associated with this Community News record.</description>
        <label>Community News</label>
        <referenceTo>Community_News__c</referenceTo>
        <relationshipLabel>News Tags</relationshipLabel>
        <relationshipName>Community_News_Tag</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Community_Tag__c</fullName>
        <description>Defines the tag that is being associated with the News record.</description>
        <label>Community Tag</label>
        <referenceTo>Community_Tag__c</referenceTo>
        <relationshipLabel>News Items Tagged</relationshipLabel>
        <relationshipName>Community_NewItems_Tagged</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Community News Tag</label>
    <nameField>
        <displayFormat>CNT-{yy}{mm}{0}</displayFormat>
        <label>Community News Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community News Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>All custom settings for the Community will be stored within this object.</description>
    <fields>
        <fullName>News_Max_Sticky__c</fullName>
        <description>An organization can define a maximum number of &quot;sticky&quot; (featured) Community News records that are actively published the Community.</description>
        <label>News Max Sticky</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/objects/Community_Tag__c.object
<CustomObject>
    <description>Define a library of Tags that will help categorize interests for the Community.  Tags can be associated to Community News, Events, Groups, and Contacts via separate junction objects.  This will allow the starter pack to recommend items to a Community user.</description>
    <fields>
        <fullName>Community_Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the Theme of the Community Tag.</description>
        <inlineHelpText>Represents the Theme of the Community Tag.</inlineHelpText>
        <label>Community Theme</label>
        <referenceTo>Community_Theme__c</referenceTo>
        <relationshipLabel>Community Tags</relationshipLabel>
        <relationshipName>Community_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tag_Theme_UniqueID__c</fullName>
        <description>Coming Soon.</description>
        <inlineHelpText>Coming Soon.</inlineHelpText>
        <label>Tag-Theme UniqueID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Community Tag</label>
    <nameField>
        <label>Community Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community_Theme__c.object
<CustomObject>
    <description>Will be used to roll up Tags to a Theme.  Depending on attributes of the Theme, related Tags may be used in the Community Registration process or available to associate to Resources.</description>
    <label>Community Theme</label>
    <nameField>
        <label>Community Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CommunityNewsController.cls
public with sharing class CommunityNewsController {

	public class CommunityNewsException extends Exception {}

	// -- common variables --
	public String imgPrefix {
		get {
			if (imgPrefix == NULL) {
				imgPrefix = '';
				Id nId = Network.getNetworkId();
				if (nId != NULL) {
					Network nRec = [SELECT UrlPathPrefix FROM Network WHERE Id = :nId];
					imgPrefix = '/' + nRec.UrlPathPrefix;
				}
			}
			return imgPrefix;
		}
		set;
	}

	private ApexPages.StandardController stdctrl;
	private String mode;

	// CONSTRUCTOR
	public CommunityNewsController(ApexPages.StandardController stdController) {
		stdctrl = stdController;
	}

	public CommunityNewsController() {
	}

	// INIT MAP SECTION
	public void initFromEdit() {
		mode = 'edit';
		init();
	}

	public void initFromView() {
		mode = 'view';
		init();
	}

	public void initFromList() {
		mode = 'list';
		initList();
	}

	// CREATE, EDIT, DETAIL SECTION

	// -- variables --
	public Community_News__c news { get;set; }
	public Blob imgBody { get;set; }
	public String imgFileName { get;set; }
	public String imgContentType { get;set; }
	public Integer rowspanCount { get;set; }

	private String TAGS_INPUT_NAME = 'tags';

	// -- methods --
	private void init() {
		news = (Community_News__c)stdctrl.getRecord();
		if (news.Id != NULL) {
			Set<String> collectedFields = new Set<String> {
					'Id', 'Name', 'Image_Path__c', 'Title__c', 'Teaser__c', 'Content__c', 'URL__c', 'Allow_Comments__c', 'Comment_Expiration_Date__c',
					'Make_Entry_Sticky__c', 'Entry_Date__c', 'Expiration_Date__c', 'Type__c', 'Content__c'
						};
			for (Schema.FieldSetMember f : fieldset) {
				collectedFields.add(f.getFieldPath());
			}
			String query = '';
			String sep = 'SELECT ';
			List<String> cfAsList = new List<String>();
			cfAsList.addAll(collectedFields);
			for (String cfItem : cfAsList) {
				query += sep + cfItem;
				sep = ', ';
			}
			query += ' FROM Community_News__c WHERE Id = \'' + news.Id + '\'';
			news = Database.query(query);
		}
		else {
			news.Entry_Date__c = Datetime.now();
		}
	}

	public PageReference cancel() {
		return stdctrl.cancel();
	}

	public PageReference edit() {
		return stdctrl.edit();
	}

	public PageReference submit() {
		try {
			Community_Settings__c cs = Community_Settings__c.getInstance();
			if (news.Make_Entry_Sticky__c == true && cs != NULL && cs.News_Max_Sticky__c != NULL) {
				Datetime startDate = news.Entry_Date__c;
				Datetime endDate = news.Expiration_Date__c;
				Id newsId = news.Id;
				String nmsQuery = 'SELECT Id FROM Community_News__c WHERE Entry_Date__c <= :endDate AND Expiration_Date__c >= :startDate';
				nmsQuery += (newsId == NULL) ? ' AND Make_Entry_Sticky__c = true' : ' AND (Make_Entry_Sticky__c = true OR (Make_Entry_Sticky__c != true AND Id = :newsId))';
				List<Community_News__c> cnList = Database.query(nmsQuery);
				if (cnList.size() > Integer.valueOf(cs.News_Max_Sticky__c)) {
					throw new CommunityNewsException(Label.ERR_News_Too_Many_Sticky);
				}
			}
			if (news.Type__c == 'External') {
				news.Content__c = NULL;
			}
			upsert news;
			if (imgBody != NULL && String.isNotBlank(imgFileName)) {
				Attachment aTemp = new Attachment(Name='Thumbnail_' + imgFileName, Body=imgBody, ParentId=news.Id, ContentType=imgContentType);
				insert aTemp;
				news.Image_Path__c = '/servlet/servlet.FileDownload?file=' + aTemp.Id;
				update news;
			}
			String tagsIdsString = ApexPages.currentPage().getParameters().get(TAGS_INPUT_NAME);
			CommunityTagSelectorController ctsc = new CommunityTagSelectorController();
			ctsc.objectId = news.Id;
			ctsc.objectType = Community_News_Tag__c.getSObjectType().getDescribe().getName();
			ctsc.filterName = Community_News_Tag__c.Community_News__c.getDescribe().getName();
			ctsc.saveTags(tagsIdsString);
			return stdctrl.cancel();
		}
		catch (Exception e) {
			ApexPages.addMessages(e);
		}
		return NULL;
	}

	public List<Schema.FieldSetMember> fieldset {
		get {
			List<Schema.FieldSetMember> resultList;
			if (mode == 'edit') {
				resultList = SObjectType.Community_News__c.FieldSets.EditNews.getFields();
			}
			else {
				resultList = new List<Schema.FieldSetMember>();
				rowspanCount = 0;
				Boolean contentFieldNotFound = true;
				for (Schema.FieldSetMember f2 : SObjectType.Community_News__c.FieldSets.ViewNews.getFields()) {
					resultList.add(f2);
					rowspanCount += contentFieldNotFound ? 1 : 0;
					contentFieldNotFound = contentFieldNotFound && f2.getFieldPath() != 'Content__c';
				}
			}
			return resultList;
		}
	}

	public Boolean allowComments {
		get {
			return news.Allow_Comments__c == true && (news.Comment_Expiration_Date__c == NULL || news.Comment_Expiration_Date__c > Datetime.now());
		}
	}

	public String urlForEditNews {
		get {
			return prepareUrl(Page.CommunityNewsEdit.getUrl())
					+ '?id=' + news.Id + '&retURL='
					+ EncodingUtil.urlEncode(prepareUrl(Page.CommunityNewsDetail.getUrl()) + '?id=' + news.Id, 'UTF-8');
		}
	}

	public String urlForNewNews {
		get {
			return prepareUrl(Page.CommunityNewsEdit.getUrl())
					+ '?&retURL='
					+ EncodingUtil.urlEncode(prepareUrl(Page.CommunityNews.getUrl()), 'UTF-8');
		}
	}

	private String prepareUrl(String inUncouthUrl) {
		return String.isNotBlank(Site.getPathPrefix()) ? inUncouthUrl.replace('/apex/', Site.getPathPrefix() + '/') : inUncouthUrl;
	}

	// LIST SECTION
	// -- variables --
	public List<Community_News__c> newsPage { get;set; }
	public Integer newsPageNumber { get;set; }
	public Integer newsPagesTotal { get;set; }
	public Boolean newsHasNext { get;set; }
	public Boolean newsHasPrevious { get;set; }
	public Map<String, List<Tag>> tagsMap { get; set; }

	private Integer NEWS_PAGE_SIZE = 25;
	private String TAGS_FILTER_NAME = 't';

	// -- methods --
	private void initList() {
		List<String> communityNewsIdList = new List<String>();

		String nQuery = 'SELECT Id, Image_Path__c, Title__c, Teaser__c FROM Community_News__c';
		nQuery += ' WHERE Entry_Date__c <= TODAY AND Expiration_Date__c > TODAY AND Breaking_News__c = false';
		Set<Id> cnIds = new Set<Id>();
		try {
			String tagsIdsString2 = ApexPages.currentPage().getParameters().get(TAGS_FILTER_NAME);
			if (String.isNotBlank(tagsIdsString2)) {
				Id tagId = Id.valueOf(tagsIdsString2);
				for (Community_News_Tag__c cnt : [
							SELECT Community_News__c FROM Community_News_Tag__c
							WHERE Community_News__r.Entry_Date__c <= TODAY AND Community_News__r.Expiration_Date__c > TODAY
							AND Community_News__r.Breaking_News__c = false AND Community_Tag__c = :tagId
								]) {
					cnIds.add(cnt.Community_News__c);
				}
				if (cnIds.size() > 0) {
					nQuery += ' AND Id IN :cnIds';
				}
			}
		}
		catch (Exception e) {
			//TO DO: Create Filter Error Message
		}
		nQuery += ' ORDER BY Make_Entry_Sticky__c, Entry_Date__c DESC';
		List<Community_News__c> nQueryList = database.query(nQuery);
		Integer nqlSize = nQueryList.size();
		newsPagesTotal = nqlSize / NEWS_PAGE_SIZE + ((Math.mod(nqlSize, NEWS_PAGE_SIZE) == 0) ? 0 : 1);
		newsPagesTotal = newsPagesTotal == 0 ? 1 : newsPagesTotal;
		newsPageNumber = newsPageNumber == NULL ? 1 : newsPageNumber;
		newsHasNext = newsPageNumber < newsPagesTotal;
		newsHasPrevious = newsPageNumber > 1;
		Integer startCopyInterval = newsPageNumber > 1 ? ((newsPageNumber - 1) * NEWS_PAGE_SIZE) : 0;
		Integer endCopyInterval = (nqlSize <= (startCopyInterval + NEWS_PAGE_SIZE)) ? nqlSize : (startCopyInterval + NEWS_PAGE_SIZE);
		newsPage = new List<Community_News__c>();
		for (Integer ii = startCopyInterval; ii < endCopyInterval; ii++) {
			newsPage.add(nQueryList[ii]);
			communityNewsIdList.add(nQueryList[ii].Id);
		}
		tagsMap = getTags(Page.CommunityNews.getUrl(), communityNewsIdList);
	}

	public void newsNextPage() {
		newsPageNumber++;
		initList();
	}

	public void newsLastPage() {
		newsPageNumber = newsPagesTotal;
		initList();
	}

	public void newsPreviousPage() {
		newsPageNumber--;
		initList();
	}

	public void newsFirstPage() {
		newsPageNumber = 0;
		initList();
	}

	private Map<String, List<Tag>> getTags(String rPage, List<String> communityNewsIdList) {

		Map<String, List<Tag>> result = new Map<String, List<Tag>>();
		Map<String, List<String>> eventsAndTagsMap = new Map<String, List<String>>();
		Map<Id, Community_Tag__c> communityTagsMap = new Map<Id, Community_Tag__c>();

		String query = 'SELECT Id, Community_Tag__c, Community_News__c FROM Community_News_Tag__c WHERE Community_News__c IN: communityNewsIdList';
		List<SObject> sObjectList = Database.query(query);
		Set<String> tagIds = new Set<String>();
		for (SObject objItem : sObjectList) {
			tagIds.add((String) objItem.get('Community_Tag__c'));
			String communityEventId = (String) objItem.get('Community_News__c');
			if (eventsAndTagsMap.get(communityEventId) == NULL) {
				eventsAndTagsMap.put(communityEventId, new List<String>{(String) objItem.get('Community_Tag__c')});
			}
			else {
				eventsAndTagsMap.get(communityEventId).add((String) objItem.get('Community_Tag__c'));
			}

		}
		communityTagsMap = new Map<Id, Community_Tag__c>([
			SELECT Id, Name, Tag_Theme_UniqueID__c, Community_Theme__r.Name
			FROM Community_Tag__c
			WHERE Id IN :tagIds
		]);
		for (String Item : eventsAndTagsMap.keySet()) {

			for (String  eventsAndTagsMapItem : eventsAndTagsMap.get(Item)) {
				Community_Tag__c CommunityTagItem = communityTagsMap.get(eventsAndTagsMapItem);
				Tag tag = new Tag();
				tag.Name = CommunityTagItem.Community_Theme__r.Name + ' > ' + CommunityTagItem.Name;
				tag.Url = rPage + '?t=' + CommunityTagItem.Id;

				if (result.get(Item) != NULL) {
					result.get(Item).add(tag);
				}
				else {
					result.put(Item, new List<Tag>{tag});
				}
			}

		}
		for (String Item : communityNewsIdList) {
			if (result.get(Item) == NULL) {
				Tag tag = new Tag();
				tag.Name = '';
				tag.Url = 'null';
				result.put(Item, new List<Tag>{tag});
			}

		}

		return result;
	}

	public class Tag {
		public String Url { get; set; }
		public String Name { get; set; }
	}
}