src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Role__c</fullName>
        <description>This field describes the primary role or user experience in the Community.  The values of this field should match those of Community_Profile__c.RecordType.Name</description>
        <label>Primary Role</label>
        <picklist>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty/Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alumni</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Community_Contact_ID__c</fullName>
        <description>Populate the 18 digit Salesforce ID of this User&apos;s Contact record.  This is used to define the Community Profile fields that are displayed for this user. Only use this field if the User is a full Salesforce licensed user and not a Community-only user.</description>
        <label>Community Contact ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CommunityFeed_PeopleController.cls
public with sharing class CommunityFeed_PeopleController extends CommunityFeedBase {

	public CommunityFeed_PeopleController() {
	}
	@RemoteAction
	public static List<ChatterGroupMember> getPeoples() {
		List<ChatterGroupMember> peoples = new List<ChatterGroupMember>();
		List<EntitySubscription> followings = [
			Select SubscriberId, ParentId, IsDeleted, Id, CreatedDate, CreatedById
			From EntitySubscription
			WHERE SubscriberId =:Userinfo.getUserId()
			AND IsDeleted = false
			LIMIT 1000
		];
		Set<Id> followingsIds = new Set<Id>();
		for (EntitySubscription subscription : followings) {
			followingsIds.add(subscription.ParentId);
		}
		for (User u : [
				SELECT Id, Name, FirstName, LastName, SmallPhotoUrl, FullPhotoUrl, ContactId, Contact.Primary_Role__c
				FROM User 
				WHERE (ContactId != NULL OR Community_Contact_ID__c != NULL) 
				AND isActive = true 
				AND Id != :UserInfo.getUserId()
				ORDER BY Name ASC
		]) {
			peoples.add(new ChatterGroupMember(u, followingsIds.contains(u.Id)));
		}
		return peoples;
	}

	@RemoteAction
	public static Boolean subscriberAction(Id memberId, Boolean isSubscribe) {
		if (!isSubscribe) {
			List<EntitySubscription> followings = [
				Select SubscriberId, ParentId, IsDeleted, Id, CreatedDate, CreatedById
				From EntitySubscription
				WHERE SubscriberId =:Userinfo.getUserId()
				AND ParentId = :memberId
				LIMIT 1
			];
			if (!followings.isEmpty()) {
				ConnectApi.Chatter.deleteSubscription(CommunityGroupsBase.getCurrentCommunityId(), followings[0].Id);
			}
		} else if (isSubscribe) {
			ConnectApi.ChatterUsers.follow(CommunityGroupsBase.getCurrentCommunityId(), 'me', memberId);
		}
		return true;
	}
}